/*
 * CounterClass.cpp
 *
 *  Created on: Jul 14, 2015
 *      Author: cnpaul
 */

#include "CounterClass.h"
namespace alicaAutogenerated
{
	int CounterClass::called = 0;
	CounterClass::CounterClass() {
		// TODO Auto-generated constructor stub

	}

	CounterClass::~CounterClass() {
		// TODO Auto-generated destructor stub
	}

}
