#ifndef VHMaster_H_
#define VHMaster_H_

#include "DomainCondition.h"
#include "engine/BasicUtilityFunction.h"
#include "engine/DefaultUtilityFunction.h"
#include "engine/UtilityFunction.h"
/*PROTECTED REGION ID(incl1524452721452) ENABLED START*/
// Add inlcudes here
/*PROTECTED REGION END*/
using namespace alica;

namespace alicaAutogenerated
{
/*PROTECTED REGION ID(meth1524452721452) ENABLED START*/
// Add other things here
/*PROTECTED REGION END*/
class UtilityFunction1524452721452 : public BasicUtilityFunction
{
    shared_ptr<UtilityFunction> getUtilityFunction(Plan* plan);
};

class RunTimeCondition1524463006078 : public DomainCondition
{
    bool evaluate(shared_ptr<RunningPlan> rp);
};

} /* namespace alica */

#endif
