#include "Plans/VariableHandling/constraints/Lvl11524452759599Constraints.h"
using namespace std;
using namespace alica;
/*PROTECTED REGION ID(ch1524452759599) ENABLED START*/
// Add additional using directives here
#include <assert.h>
#include <autodiff/AutoDiff.h>
#include <engine/constraintmodul/ProblemDescriptor.h>
using autodiff::TermPtr;

/*PROTECTED REGION END*/

namespace alicaAutogenerated
{
// Plan:Lvl1

/*
 * Tasks:
 * - EP:1524452759601 : DefaultTask (1225112227903)
 *
 * States:
 * - NewState (1524452759600)
 * - NewState (1524453481856)
 *
 * Vars:
 * - L1A (1524453326397)
 * - L1B (1524453331530)
 * - L1C (1524453336548)
 */

/*
 * RuntimeCondition - (Name): NewRuntimeCondition
 * (ConditionString):
 * Static Variables: [L1A, L1B]
 * Domain Variables:

 */
void Constraint1524453470580::getConstraint(shared_ptr<ProblemDescriptor> c, shared_ptr<RunningPlan> rp)
{
    /*PROTECTED REGION ID(cc1524453470580) ENABLED START*/
    TermPtr l1a = static_cast<autodiff::Variable*>(c->getStaticVars()[0]);
    TermPtr l1b = static_cast<autodiff::Variable*>(c->getStaticVars()[1]);
    assert(c->getStaticVars().size() == 2);
    assert(c->getStaticRanges().size() == 2);
    assert(c->getDomainVars().empty());
    c->editStaticRanges()[0].setMin(-200.0);
    c->editStaticRanges()[0].setMax(-100.0);

    c->editStaticRanges()[1].setMin(100.0);
    c->editStaticRanges()[1].setMax(200.0);

    TermPtr constraint = l1a + l1b < l1b->getOwner()->constant(10.0);
    constraint &= l1a + l1b > l1b->getOwner()->constant(-10.0);

    c->setConstraint(constraint);

    TermPtr utility = l1b->getOwner()->constant(1);
    c->setUtility(utility);
    c->setUtilitySufficiencyThreshold(10.0);

    /*PROTECTED REGION END*/
}

// State: NewState

// State: NewState

// State: NewState

// State: NewState

/*
 * Transition:
 * - Name: MISSING_NAME
 * - ConditionString:
 *
 * Plans in State:
 * Static Variables: []
 * Domain Variables:

 * forall agents in MISSING_NAME let v = [X, Y]

 */
void Constraint1524453491764::getConstraint(shared_ptr<ProblemDescriptor> c, shared_ptr<RunningPlan> rp)
{
    /*PROTECTED REGION ID(cc1524453491764) ENABLED START*/
    assert(c->getStaticVars().empty());
    assert(c->getStaticRanges().empty());
    assert(c->getDomainVars().size() == 2);

    TermPtr x1 = static_cast<autodiff::Variable*>(c->getDomainVars()[0].getVars()[0].var);
    TermPtr y1 = static_cast<autodiff::Variable*>(c->getDomainVars()[0].getVars()[1].var);

    TermPtr x2 = static_cast<autodiff::Variable*>(c->getDomainVars()[1].getVars()[0].var);
    TermPtr y2 = static_cast<autodiff::Variable*>(c->getDomainVars()[1].getVars()[1].var);

    TermPtr constraint = (x1 - x2) * (x1 - x2) + (y1 - y2) * (y1 - y2) > x1->getOwner()->constant(10000.0);
    constraint &= x1 > y1;
    constraint &= x2 > y2;

    c->setConstraint(constraint);
    TermPtr utility = x1->getOwner()->constant(1.0);

    c->setUtility(utility);
    /*PROTECTED REGION END*/
}
}
