#include "Plans/VariableHandling/constraints/Lvl21524452793378Constraints.h"
using namespace std;
using namespace alica;
/*PROTECTED REGION ID(ch1524452793378) ENABLED START*/
#include <AutoDiff.h>
#include <assert.h>
#include <engine/constraintmodul/ProblemDescriptor.h>

/*PROTECTED REGION END*/

namespace alicaAutogenerated
{
// Plan:Lvl2

/*
 * Tasks:
 * - EP:1524452793380 : DefaultTask (1225112227903)
 * - EP:1524453238753 : AttackTask (1407153522080)
 *
 * States:
 * - NewState (1524452793379)
 * - Dummy (1524453248579)
 *
 * Vars:
 * - L2A (1524453150187)
 * - L2B (1524453155043)
 * - L2C (1524453162883)
 */

/*
 * RuntimeCondition - (Name): NewRuntimeCondition
 * (ConditionString):
 * Static Variables: [L2A, L2B, L2C]
 * Domain Variables:

 * forall agents in Dummy let v = [X, Y]

 */
void Constraint1524453266123::getConstraint(shared_ptr<ProblemDescriptor> c, shared_ptr<RunningPlan> rp)
{
    /*PROTECTED REGION ID(cc1524453266123) ENABLED START*/
    /*PROTECTED REGION ID(cc1524452937477) ENABLED START*/
    assert(c->getStaticVars().size() == 3);
    assert(c->getStaticRanges().size() == 3);
    assert(c->getDomainVars().size() == 1);
    assert(c->getDomainVars()[0].getVars().size() == 2);

    std::shared_ptr<autodiff::Term> x = std::static_pointer_cast<autodiff::Variable>(c->getDomainVars()[0].getVars()[0].var);
    std::shared_ptr<autodiff::Term> y = std::static_pointer_cast<autodiff::Variable>(c->getDomainVars()[0].getVars()[1].var);

    c->editDomainVars()[0].editVars()[0].min = 50.0;
    c->editDomainVars()[0].editVars()[1].min = 50.0;
    c->editDomainVars()[0].editVars()[0].max = 150.0;
    c->editDomainVars()[0].editVars()[1].max = 150.0;

    shared_ptr<autodiff::Term> constraint = x > y;

    c->setConstraint(constraint);
    std::shared_ptr<autodiff::Term> utility = x + y;

    c->setUtility(utility);
    c->setUtilitySufficiencyThreshold(280.0);

    /*PROTECTED REGION END*/
    /*PROTECTED REGION END*/
}

// State: NewState

// State: NewState

// State: Dummy

// State: Dummy
}
