package de.unikassel.vs.alica.planDesigner.alicamodel;

import javafx.beans.property.SimpleStringProperty;

public class Variable extends PlanElement {

    protected final SimpleStringProperty variableType = new SimpleStringProperty(null, "variableType", "");

    /**
     * Need to be explicitly written, because the constructor Variable(AbstractPlan parentPlan)
     * makes the autogenerated version of this one vanishing.
     */
    public Variable() {
        super();
    }

    /**
     * Constructor for representing incomplete Variable References while parsing files.
     * @param id The ID found in the file, while parsing the reference.
     */
    public Variable(long id) {
        this();
        this.id = id ;
    }

    public String getVariableType() { return variableType.get(); }
    public void setVariableType(String variableType) { this.variableType.set(variableType); }
    public SimpleStringProperty variableTypeProperty() {
        return variableType;
    }

    public void registerDirtyFlag(ChangeListenerForDirtyFlag listener) {
        this.nameProperty().addListener(listener);
        this.commentProperty().addListener(listener);
        this.variableTypeProperty().addListener(listener);
    }
}
