#ifndef GSolverTestPlanCONSTRAINT_H_
#define GSolverTestPlan_H_
#include "engine/BasicConstraint.h"
#include <memory>

using namespace std;
using namespace alica;

namespace alica
{
    class ConstraintDescriptor;
    class RunningPlan;
}

namespace alicaAutogenerated
{

    class Constraint1417424512343 : public BasicConstraint
    {
        void getConstraint(shared_ptr<ConstraintDescriptor> c, shared_ptr<RunningPlan>);
    };

} /* namespace alica */

#endif /* GSolverTestPlanCONSTRAINT_H_ */
