#ifndef GSolverMasterCONSTRAINT_H_
#define GSolverMaster_H_
#include "engine/BasicConstraint.h"
#include <memory>

using namespace std;
using namespace alica;

namespace alica
{
    class ConstraintDescriptor;
    class RunningPlan;
}

namespace alicaAutogenerated
{

} /* namespace alica */

#endif /* GSolverMasterCONSTRAINT_H_ */
