using namespace std;
using namespace alicaAutogenerated;

#include <iostream>
#include "UtilityFunctionCreator.h"

#include  "PlanThree1407153663917.h"

#include  "GoalPlan1402488870347.h"

#include  "SimpleTestPlan1412252439925.h"

#include  "PlanOne1407153611768.h"

#include  "AttackPlan1402488634525.h"

#include  "PlanTwo1407153645238.h"

#include  "MasterPlanTaskAssignment1407152758497.h"

#include  "PlanFive1407153703092.h"

#include  "Tackle1402489318663.h"

#include  "PlanFour1407153683051.h"

#include  "MidFieldPlayPlan1402488770050.h"

#include  "Defend1402488893641.h"

#include  "MasterPlan1402488437260.h"

namespace alica {

UtilityFunctionCreator::~UtilityFunctionCreator() {
}

UtilityFunctionCreator::UtilityFunctionCreator() {
}

shared_ptr<BasicUtilityFunction> createUtility(long utilityfunctionConfId) {
  switch (utilityfunctionConfId) {

    case 1407153663917
    return make_shared<UtilityFunction1407153663917>();
    break;

    case 1402488870347
    return make_shared<UtilityFunction1402488870347>();
    break;

    case 1412252439925
    return make_shared<UtilityFunction1412252439925>();
    break;

    case 1407153611768
    return make_shared<UtilityFunction1407153611768>();
    break;

    case 1402488634525
    return make_shared<UtilityFunction1402488634525>();
    break;

    case 1407153645238
    return make_shared<UtilityFunction1407153645238>();
    break;

    case 1407152758497
    return make_shared<UtilityFunction1407152758497>();
    break;

    case 1407153703092
    return make_shared<UtilityFunction1407153703092>();
    break;

    case 1402489318663
    return make_shared<UtilityFunction1402489318663>();
    break;

    case 1407153683051
    return make_shared<UtilityFunction1407153683051>();
    break;

    case 1402488770050
    return make_shared<UtilityFunction1402488770050>();
    break;

    case 1402488893641
    return make_shared<UtilityFunction1402488893641>();
    break;

    case 1402488437260
    return make_shared<UtilityFunction1402488437260>();
    break;

  default:
    cerr << "UtilityFunctionCreator: Unknown utility requested: "
        << utilityfunctionConfId << endl;
    throw new exception();
    break;
  }
}

}
