#ifndef ConstraintTestMasterCONSTRAINT_H_
#define ConstraintTestMaster_H_
#include "engine/BasicConstraint.h"
#include <memory>

using namespace std;
using namespace alica;

namespace alica
{
class ProblemDescriptor;
class RunningPlan;
} // namespace alica

namespace alicaAutogenerated
{
} // namespace alicaAutogenerated

#endif /* ConstraintTestMasterCONSTRAINT_H_ */
