#ifndef RealMasterPlanForSyncTestCONSTRAINT_H_
#define RealMasterPlanForSyncTest_H_
#include "engine/BasicConstraint.h"
#include <memory>

using namespace std;
using namespace alica;

namespace alica
{
class ProblemDescriptor;
class RunningPlan;
} // namespace alica

namespace alicaAutogenerated
{
} // namespace alicaAutogenerated

#endif /* RealMasterPlanForSyncTestCONSTRAINT_H_ */
