#ifndef AuthorityTestCONSTRAINT_H_
#define AuthorityTest_H_
#include "engine/BasicConstraint.h"
#include <memory>

using namespace std;
using namespace alica;

namespace alica
{
class ConstraintDescriptor;
class RunningPlan;
}

namespace alicaAutogenerated
{

} /* namespace alica */

#endif /* AuthorityTestCONSTRAINT_H_ */
