#ifndef AuthorityTestMasterCONSTRAINT_H_
#define AuthorityTestMaster_H_
#include "engine/BasicConstraint.h"
#include <memory>

using namespace std;
using namespace alica;

namespace alica
{
class ConstraintDescriptor;
class RunningPlan;
}

namespace alicaAutogenerated
{

} /* namespace alica */

#endif /* AuthorityTestMasterCONSTRAINT_H_ */
