#ifndef AuthorityTestMasterCONSTRAINT_H_
#define AuthorityTestMaster_H_
#include "engine/BasicConstraint.h"
#include <memory>

using namespace std;
using namespace alica;

namespace alica
{
class ConstraintDescriptor;
class RunningPlan;
}

namespace alicaAutogenerated
{

class Constraint1414403842622 : public BasicConstraint
{
  void getConstraint(shared_ptr<ConstraintDescriptor> c, shared_ptr<RunningPlan>);
};

} /* namespace alica */

#endif /* AuthorityTestMasterCONSTRAINT_H_ */
