#ifndef BehaviourTriggerTestPlan_H_
#define BehaviourTriggerTestPlan_H_

#include "DomainCondition.h"
#include "engine/BasicUtilityFunction.h"
#include "engine/UtilityFunction.h"
#include "engine/DefaultUtilityFunction.h"
/*PROTECTED REGION ID(incl1428508768572) ENABLED START*/
//Add inlcudes here
/*PROTECTED REGION END*/
using namespace alica;

namespace alicaAutogenerated
{
    /*PROTECTED REGION ID(meth1428508768572) ENABLED START*/
    //Add other things here
    /*PROTECTED REGION END*/
    class UtilityFunction1428508768572 : public BasicUtilityFunction
    {
        shared_ptr<UtilityFunction> getUtilityFunction(Plan* plan);
    };

} /* namespace alica */

#endif
