#ifndef MasterPlanTaskAssignment_H_
#define MasterPlanTaskAssignment_H_

#include "engine/BasicCondition.h"
#include "engine/BasicUtilityFunction.h"
#include "engine/UtilityFunction.h"
#include "engine/DefaultUtilityFunction.h"
/*PROTECTED REGION ID(incl1407152758497) ENABLED START*/
//Add inlcudes here
/*PROTECTED REGION END*/
using namespace alica;

namespace alicaAutogenerated
{
/*PROTECTED REGION ID(meth1407152758497) ENABLED START*/
//Add other things here
/*PROTECTED REGION END*/
class UtilityFunction1407152758497 : public BasicUtilityFunction
{
  shared_ptr<UtilityFunction> getUtilityFunction(Plan* plan);
};

} /* namespace alica */

#endif
