#ifndef Lvl2CONSTRAINT_H_
#define Lvl2_H_
#include "engine/BasicConstraint.h"
#include <memory>

using namespace std;
using namespace alica;

namespace alica
{
class ProblemDescriptor;
class RunningPlan;
} // namespace alica

namespace alicaAutogenerated
{

class Constraint1524453266123 : public BasicConstraint
{
    void getConstraint(shared_ptr<ProblemDescriptor> c, shared_ptr<RunningPlan> rp);
};

} // namespace alicaAutogenerated

#endif /* Lvl2CONSTRAINT_H_ */
