#include "Plans/VariableHandling/constraints/VHMaster1524452721452Constraints.h"
using namespace std;
using namespace alica;
/*PROTECTED REGION ID(ch1524452721452) ENABLED START*/
// Add additional using directives here
/*PROTECTED REGION END*/

namespace alicaAutogenerated
{
// Plan:VHMaster

/*
 * Tasks:
 * - EP:1524452721454 : DefaultTask (1225112227903)
 *
 * States:
 * - NewState (1524452721453)
 *
 * Vars:
 * - MA (1524463022262)
 * - MB (1524463028066)
 */

/*
 * RuntimeCondition - (Name): NewRuntimeCondition
 * (ConditionString): VHMaster Runtime Condition
 * Static Variables: [MA, MB]
 * Domain Variables:

 */
void Constraint1524463006078::getConstraint(shared_ptr<ProblemDescriptor> c, shared_ptr<RunningPlan> rp)
{
    /*PROTECTED REGION ID(cc1524463006078) ENABLED START*/
    /*PROTECTED REGION END*/
}

// State: NewState

// State: NewState
} // namespace alicaAutogenerated
