#include "Plans/RequiresTwo1530005027592.h"
using namespace alica;
/*PROTECTED REGION ID(eph1530005027592) ENABLED START*/ // Add additional using directives here
/*PROTECTED REGION END*/
namespace alicaAutogenerated
{
// Plan:RequiresTwo

/* generated comment

 Task: DefaultTask  -> EntryPoint-ID: 1530005027594

 Task: DefaultTask  -> EntryPoint-ID: 1530005035065

 */
shared_ptr<UtilityFunction> UtilityFunction1530005027592::getUtilityFunction(Plan* plan)
{
    /*PROTECTED REGION ID(1530005027592) ENABLED START*/

    shared_ptr<UtilityFunction> defaultFunction = make_shared<DefaultUtilityFunction>(plan);
    return defaultFunction;

    /*PROTECTED REGION END*/
}

// State: NewState in Plan: RequiresTwo

// State: NewState in Plan: RequiresTwo
} // namespace alicaAutogenerated
