#include "ConditionCreator.h"

#include "Plans/ProblemModule/ProbBuildingLevel1_11479557664989.h"

#include "Plans/VariableHandling/Lvl21524452793378.h"

#include "Plans/GSolver/GSolverTestPlan1417423757243.h"

#include "Plans/VariableHandling/Lvl11524452759599.h"

#include "Plans/ProblemModule/QueryPlan11479556074049.h"

#include "Plans/ProblemModule/QueryPlan21479718449392.h"

#include "Plans/VariableHandling/Lvl31524452836022.h"

#include "Plans/ProblemModule/ProblemBuildingMaster1479556022226.h"

#include "Plans/GSolver/GSolverMaster1417423751087.h"

#include "Plans/ProblemModule/ProbBuildingLevel11479557378264.h"

#include "Plans/VariableHandling/VHMaster1524452721452.h"

using namespace alicaAutogenerated;
namespace alica
{

ConditionCreator::ConditionCreator() {}
ConditionCreator::~ConditionCreator() {}

shared_ptr<BasicCondition> ConditionCreator::createConditions(long conditionConfId)
{
    switch (conditionConfId) {

    case 1524453266123:

        return make_shared<RunTimeCondition1524453266123>();

        break;

    case 1417424512343:

        return make_shared<RunTimeCondition1417424512343>();

        break;

    case 1524453470580:

        return make_shared<RunTimeCondition1524453470580>();

        break;

    case 1524453491764:

        return make_shared<TransitionCondition1524453491764>();

        break;

    case 1479556084493:

        return make_shared<RunTimeCondition1479556084493>();

        break;

    case 1524452937477:

        return make_shared<RunTimeCondition1524452937477>();

        break;

    case 1479557592662:

        return make_shared<TransitionCondition1479557592662>();

        break;

    case 1524463006078:

        return make_shared<RunTimeCondition1524463006078>();

        break;

    default:
        cerr << "ConditionCreator: Unknown condition id requested: " << conditionConfId << endl;
        throw new exception();
        break;
    }
}
} // namespace alica
