#include "ConstraintCreator.h"
#include <iostream>

#include "Plans/ProblemModule/constraints/ProbBuildingLevel1_11479557664989Constraints.h"

#include "Plans/VariableHandling/constraints/Lvl21524452793378Constraints.h"

#include "Plans/GSolver/constraints/GSolverTestPlan1417423757243Constraints.h"

#include "Plans/VariableHandling/constraints/Lvl11524452759599Constraints.h"

#include "Plans/ProblemModule/constraints/QueryPlan11479556074049Constraints.h"

#include "Plans/ProblemModule/constraints/QueryPlan21479718449392Constraints.h"

#include "Plans/VariableHandling/constraints/Lvl31524452836022Constraints.h"

#include "Plans/ProblemModule/constraints/ProblemBuildingMaster1479556022226Constraints.h"

#include "Plans/GSolver/constraints/GSolverMaster1417423751087Constraints.h"

#include "Plans/ProblemModule/constraints/ProbBuildingLevel11479557378264Constraints.h"

#include "Plans/VariableHandling/constraints/VHMaster1524452721452Constraints.h"

using namespace std;
using namespace alicaAutogenerated;

namespace alica
{

ConstraintCreator::ConstraintCreator() {}

ConstraintCreator::~ConstraintCreator() {}

shared_ptr<BasicConstraint> ConstraintCreator::createConstraint(long constraintConfId)
{
    switch (constraintConfId) {

    case 1524453266123:
        return make_shared<Constraint1524453266123>();
        break;

    case 1417424512343:
        return make_shared<Constraint1417424512343>();
        break;

    case 1524453470580:
        return make_shared<Constraint1524453470580>();
        break;

    case 1524453491764:
        return make_shared<Constraint1524453491764>();
        break;

    case 1479556084493:
        return make_shared<Constraint1479556084493>();
        break;

    case 1524452937477:
        return make_shared<Constraint1524452937477>();
        break;

    case 1479557592662:
        return make_shared<Constraint1479557592662>();
        break;

    case 1524463006078:
        return make_shared<Constraint1524463006078>();
        break;

    default:
        cerr << "ConstraintCreator: Unknown constraint requested: " << constraintConfId << endl;
        throw new exception();
        break;
    }
}
} // namespace alica
