#include "UtilityFunctionCreator.h"
#include <iostream>

#include "Plans/ProblemModule/ProbBuildingLevel1_11479557664989.h"

#include "Plans/VariableHandling/Lvl21524452793378.h"

#include "Plans/GSolver/GSolverTestPlan1417423757243.h"

#include "Plans/VariableHandling/Lvl11524452759599.h"

#include "Plans/ProblemModule/QueryPlan11479556074049.h"

#include "Plans/ProblemModule/QueryPlan21479718449392.h"

#include "Plans/VariableHandling/Lvl31524452836022.h"

#include "Plans/ProblemModule/ProblemBuildingMaster1479556022226.h"

#include "Plans/GSolver/GSolverMaster1417423751087.h"
#include "Plans/ProblemModule/ProbBuildingLevel11479557378264.h"

#include "Plans/VariableHandling/VHMaster1524452721452.h"

using namespace std;
using namespace alicaAutogenerated;
namespace alica
{

UtilityFunctionCreator::~UtilityFunctionCreator() {}

UtilityFunctionCreator::UtilityFunctionCreator() {}

shared_ptr<BasicUtilityFunction> UtilityFunctionCreator::createUtility(long utilityfunctionConfId)
{
    switch (utilityfunctionConfId) {

    case 1479557664989:
        return make_shared<UtilityFunction1479557664989>();
        break;

    case 1524452793378:
        return make_shared<UtilityFunction1524452793378>();
        break;

    case 1417423757243:
        return make_shared<UtilityFunction1417423757243>();
        break;

    case 1524452759599:
        return make_shared<UtilityFunction1524452759599>();
        break;

    case 1479556074049:
        return make_shared<UtilityFunction1479556074049>();
        break;

    case 1479718449392:
        return make_shared<UtilityFunction1479718449392>();
        break;

    case 1524452836022:
        return make_shared<UtilityFunction1524452836022>();
        break;

    case 1479556022226:
        return make_shared<UtilityFunction1479556022226>();
        break;

    case 1417423751087:
        return make_shared<UtilityFunction1417423751087>();
        break;

    case 1479557378264:
        return make_shared<UtilityFunction1479557378264>();
        break;

    case 1524452721452:
        return make_shared<UtilityFunction1524452721452>();
        break;

    default:
        cerr << "UtilityFunctionCreator: Unknown utility requested: " << utilityfunctionConfId << endl;
        throw new exception();
        break;
    }
}
} // namespace alica
