/*
 * ConstraintTestPlan1414068524245Constraint.h
 *
 *  Created on: Oct 23, 2014
 *      Author: Philipp
 */

#ifndef CONSTRAINTTESTPLAN1414068524245CONSTRAINT_H_
#define CONSTRAINTTESTPLAN1414068524245CONSTRAINT_H_

#include "engine/BasicConstraint.h"
#include <memory>

using namespace std;
using namespace alica;

namespace alica
{
	class ConstraintDescriptor;
	class RunningPlan;
}

namespace alicaAutogenerated
{

	class Constraint1414068566297 : public BasicConstraint
	{
		void getConstraint(shared_ptr<ConstraintDescriptor> c, shared_ptr<RunningPlan> rp);
	};

} /* namespace alica */

#endif /* CONSTRAINTTESTPLAN1414068524245CONSTRAINT_H_ */
