/*
 * ConstraintTestPlan1414068524245.h
 *
 *  Created on: Oct 23, 2014
 *      Author: Philipp
 */

#ifndef CONSTRAINTTESTPLAN1414068524245_H_
#define CONSTRAINTTESTPLAN1414068524245_H_

#include "engine/BasicCondition.h"
#include "engine/BasicUtilityFunction.h"

using namespace alica;

namespace alicaAutogenerated
{
	class UtilityFunction1414068524245 : public BasicUtilityFunction
	{
		shared_ptr<UtilityFunction> getUtilityFunction(Plan* plan);
	};

	class RunTimeCondition1414068566297 : public BasicCondition
	{
	public:
		bool evaluate(shared_ptr<RunningPlan> rp);
	};

} /* namespace alica */

#endif /* CONSTRAINTTESTPLAN1414068524245_H_ */
