/*
 * MultiAgentTestMaster1413200842973.h
 *
 *  Created on: Oct 13, 2014
 *      Author: Stefan Jakob
 */

#ifndef ALICA_ALICA_TEST_MULTIAGENTTESTMASTER1413200842973_H_
#define ALICA_ALICA_TEST_MULTIAGENTTESTMASTER1413200842973_H_

#include "engine/BasicCondition.h"
#include "engine/BasicUtilityFunction.h"
#include "engine/UtilityFunction.h"
#include "engine/DefaultUtilityFunction.h"

using namespace alica;

namespace alicaAutogenerated
{

	class UtilityFunction1413200842973 : public BasicUtilityFunction
	{
		shared_ptr<UtilityFunction> getUtilityFunction(Plan* plan);
	};

	class TransitionCondition1413201227586 : public BasicCondition
	{
		bool evaluate(shared_ptr<RunningPlan> rp);
	};

	class TransitionCondition1413201389955 : public BasicCondition
	{
		bool evaluate(shared_ptr<RunningPlan> rp);
	};

} /* namespace alica */

#endif /* ALICA_ALICA_TEST_MULTIAGENTTESTMASTER1413200842973_H_ */
