/*
 * SimpleTestPlan1412252439925.h
 *
 *  Created on: Oct 8, 2014
 *      Author: Stefan Jakob
 */

#ifndef ALICA_ALICA_TEST_SRC_SIMPLETESTPLAN1412252439925_H_
#define ALICA_ALICA_TEST_SRC_SIMPLETESTPLAN1412252439925_H_

#include "engine/BasicCondition.h"
#include "engine/BasicUtilityFunction.h"
#include "engine/UtilityFunction.h"
#include "engine/DefaultUtilityFunction.h"

using namespace alica;

namespace alicaAutogenerated
{
	class UtilityFunction1412252439925 : public BasicUtilityFunction
	{
		shared_ptr<UtilityFunction> getUtilityFunction(Plan* plan);
	};


	class PreCondition1412781707952 : public BasicCondition
	{
		bool evaluate(shared_ptr<RunningPlan> rp);
	};

	class RunTimeCondition1412781693884 : public BasicCondition
	{
		bool evaluate(shared_ptr<RunningPlan> rp);
	};

	class TransitionCondition1412761926856 : public BasicCondition
	{
		bool evaluate(shared_ptr<RunningPlan> rp);
	};
} /* namespace alica */

#endif /* ALICA_ALICA_TEST_SRC_SIMPLETESTPLAN1412252439925_H_ */
