/*
 * SimpleTestPlan1412252439925Constraint.h
 *
 *  Created on: Oct 8, 2014
 *      Author: Stefan Jakob
 */

#ifndef ALICA_ALICA_TEST_SRC_SIMPLETESTPLAN1412252439925CONSTRAINT_H_
#define ALICA_ALICA_TEST_SRC_SIMPLETESTPLAN1412252439925CONSTRAINT_H_

#include "engine/BasicConstraint.h"
#include <memory>

using namespace std;
using namespace alica;

namespace alica
{
	class ConstraintDescriptor;
	class RunningPlan;
}

namespace alicaAutogenerated
{

	class Constraint1412781693884 : public BasicConstraint
	{
		void getConstraint(shared_ptr<ConstraintDescriptor> c, shared_ptr<RunningPlan>);
	};

} /* namespace alica */

#endif /* ALICA_ALICA_TEST_SRC_SIMPLETESTPLAN1412252439925CONSTRAINT_H_ */
