#include "Plans/Authority/constraints/AuthorityTestMaster1414403396328Constraints.h"
using namespace std;
using namespace alica;
/*PROTECTED REGION ID(ch1414403396328) ENABLED START*/
//Add additional using directives here
/*PROTECTED REGION END*/

namespace alicaAutogenerated
{
//Plan:AuthorityTestMaster

/*		
 * Tasks: 
 * - EP:1414403396331 : DefaultTask (1225112227903)
 *
 * States:
 * - testState (1414403396329)
 * - Init (1414403820806)
 *
 * Vars:
 */

// State: testState

// State: testState

// State: Init

// State: Init

}
