#pragma once

#include <atomic>

namespace alicaAutogenerated
{
class CounterClass
{
public:
    CounterClass();
    virtual ~CounterClass();
    static std::atomic<int> called;
};
} // namespace alicaAutogenerated
