/*
 * DummyTestSummand.h
 *
 *  Created on: Oct 29, 2014
 *      Author: Stefan Jakob
 */

#ifndef ALICA_ALICA_TEST_AUTOGENERATED_SRC_DUMMYTESTSUMMAND_H_
#define ALICA_ALICA_TEST_AUTOGENERATED_SRC_DUMMYTESTSUMMAND_H_

#include <engine/USummand.h>
#include <string>
#include <vector>

namespace supplementary
{
class AgentID;
}

namespace alica
{

class DummyTestSummand : public USummand
{
public:
    DummyTestSummand(double weight, std::string name, long id, std::vector<long>& relevantEntryPointIds);
    virtual ~DummyTestSummand();
    void cacheEvalData();
    UtilityInterval eval(IAssignment* ass);
    AgentIDConstPtr robotId;

protected:
    double sb;
    double angleBallOpp;
    double velAngle;
};

} /* namespace alica */

#endif /* ALICA_ALICA_TEST_AUTOGENERATED_SRC_DUMMYTESTSUMMAND_H_ */
