#ifndef GSolverMasterCONSTRAINT_H_
#define GSolverMaster_H_
#include "engine/BasicConstraint.h"
#include <memory>

using namespace std;
using namespace alica;

namespace alica
{
class ProblemDescriptor;
class RunningPlan;
} // namespace alica

namespace alicaAutogenerated
{
} // namespace alicaAutogenerated

#endif /* GSolverMasterCONSTRAINT_H_ */
