#ifndef GSolverTestPlanCONSTRAINT_H_
#define GSolverTestPlan_H_
#include "engine/BasicConstraint.h"
#include <memory>

using namespace std;
using namespace alica;

namespace alica
{
class ProblemDescriptor;
class RunningPlan;
} // namespace alica

namespace alicaAutogenerated
{

class Constraint1417424512343 : public BasicConstraint
{
    void getConstraint(shared_ptr<ProblemDescriptor> c, shared_ptr<RunningPlan>);
};

} // namespace alicaAutogenerated

#endif /* GSolverTestPlanCONSTRAINT_H_ */
