#ifndef HandleFailExplicit_H_
#define HandleFailExplicit_H_

#include "DomainCondition.h"
#include "engine/BasicUtilityFunction.h"
#include "engine/DefaultUtilityFunction.h"
#include "engine/UtilityFunction.h"
/*PROTECTED REGION ID(incl1530004915640) ENABLED START*/
// Add inlcudes here
/*PROTECTED REGION END*/
using namespace alica;

namespace alicaAutogenerated
{
/*PROTECTED REGION ID(meth1530004915640) ENABLED START*/
// Add other things here
/*PROTECTED REGION END*/
class UtilityFunction1530004915640 : public BasicUtilityFunction
{
    shared_ptr<UtilityFunction> getUtilityFunction(Plan* plan);
};

class TransitionCondition1530004993493 : public DomainCondition
{
    bool evaluate(shared_ptr<RunningPlan> rp);
};

class TransitionCondition1530004994611 : public DomainCondition
{
    bool evaluate(shared_ptr<RunningPlan> rp);
};

class TransitionCondition1532424093178 : public DomainCondition
{
    bool evaluate(shared_ptr<RunningPlan> rp);
};

class TransitionCondition1532424113475 : public DomainCondition
{
    bool evaluate(shared_ptr<RunningPlan> rp);
};

} // namespace alicaAutogenerated

#endif
