#ifndef HandleFailExplicitMaster_H_
#define HandleFailExplicitMaster_H_

#include "DomainCondition.h"
#include "engine/BasicUtilityFunction.h"
#include "engine/DefaultUtilityFunction.h"
#include "engine/UtilityFunction.h"
/*PROTECTED REGION ID(incl1530004940652) ENABLED START*/
// Add inlcudes here
/*PROTECTED REGION END*/
using namespace alica;

namespace alicaAutogenerated
{
/*PROTECTED REGION ID(meth1530004940652) ENABLED START*/
// Add other things here
/*PROTECTED REGION END*/
class UtilityFunction1530004940652 : public BasicUtilityFunction
{
    shared_ptr<UtilityFunction> getUtilityFunction(Plan* plan);
};

} // namespace alicaAutogenerated

#endif
