#ifndef ConstraintTestMaster_H_
#define ConstraintTestMaster_H_

#include "DomainCondition.h"
#include "engine/BasicUtilityFunction.h"
#include "engine/UtilityFunction.h"
#include "engine/DefaultUtilityFunction.h"
/*PROTECTED REGION ID(incl1414068495566) ENABLED START*/
// Add inlcudes here
/*PROTECTED REGION END*/
using namespace alica;

namespace alicaAutogenerated {
/*PROTECTED REGION ID(meth1414068495566) ENABLED START*/
// Add other things here
/*PROTECTED REGION END*/
class UtilityFunction1414068495566 : public BasicUtilityFunction {
    shared_ptr<UtilityFunction> getUtilityFunction(Plan* plan);
};

}  // namespace alicaAutogenerated

#endif
