#ifndef FailsOnOne_H_
#define FailsOnOne_H_

#include "DomainCondition.h"
#include "engine/BasicUtilityFunction.h"
#include "engine/DefaultUtilityFunction.h"
#include "engine/UtilityFunction.h"
/*PROTECTED REGION ID(incl1530069246103) ENABLED START*/
// Add inlcudes here
/*PROTECTED REGION END*/
using namespace alica;

namespace alicaAutogenerated
{
/*PROTECTED REGION ID(meth1530069246103) ENABLED START*/
// Add other things here
/*PROTECTED REGION END*/
class UtilityFunction1530069246103 : public BasicUtilityFunction
{
    shared_ptr<UtilityFunction> getUtilityFunction(Plan* plan);
};

class RunTimeCondition1530069251117 : public DomainCondition
{
    bool evaluate(shared_ptr<RunningPlan> rp);
};

} /* namespace alica */

#endif
