#ifndef PlanFive_H_
#define PlanFive_H_

#include "DomainCondition.h"
#include "engine/BasicUtilityFunction.h"
#include "engine/UtilityFunction.h"
#include "engine/DefaultUtilityFunction.h"
/*PROTECTED REGION ID(incl1407153703092) ENABLED START*/
// Add inlcudes here
/*PROTECTED REGION END*/
using namespace alica;

namespace alicaAutogenerated {
/*PROTECTED REGION ID(meth1407153703092) ENABLED START*/
// Add other things here
/*PROTECTED REGION END*/
class UtilityFunction1407153703092 : public BasicUtilityFunction {
    shared_ptr<UtilityFunction> getUtilityFunction(Plan* plan);
};

}  // namespace alicaAutogenerated

#endif
