#include "Plans/ProblemModule/constraints/ProbBuildingLevel1_11479557664989Constraints.h"
using namespace std;
using namespace alica;
/*PROTECTED REGION ID(ch1479557664989) ENABLED START*/
// Add additional using directives here
/*PROTECTED REGION END*/

namespace alicaAutogenerated {
// Plan:ProbBuildingLevel1_1

/*
 * Tasks:
 * - EP:1479557690963 : DefaultTask (1225112227903)
 *
 * States:
 * - MiddleState (1479557690962)
 *
 * Vars:
 * - PBL1_1X (1479718387346)
 * - PBL1_1Y (1479718398960)
 */

// State: MiddleState

// State: MiddleState

}  // namespace alicaAutogenerated
