#include "Plans/ProblemModule/constraints/ProbBuildingLevel11479557378264Constraints.h"
using namespace std;
using namespace alica;
/*PROTECTED REGION ID(ch1479557378264) ENABLED START*/
// Add additional using directives here
/*PROTECTED REGION END*/

namespace alicaAutogenerated {
// Plan:ProbBuildingLevel1

/*
 * Tasks:
 * - EP:1479557378266 : DefaultTask (1225112227903)
 *
 * States:
 * - PTState (1479557378265)
 *
 * Vars:
 * - PBL1X (1479557432793)
 * - PBL1Y (1479557444388)
 */

// State: PTState

// State: PTState

}  // namespace alicaAutogenerated
