#include "Plans/Master1542881176278.h"
using namespace alica;
/*PROTECTED REGION ID(eph1542881176278) ENABLED START*/  // Add additional using directives here
#include <alica_ros_turtlesim/world_model.hpp>
/*PROTECTED REGION END*/
namespace alicaAutogenerated {
// Plan:Master

/* generated comment

 Task: DefaultTask  -> EntryPoint-ID: 1543227864154

 */
shared_ptr<UtilityFunction> UtilityFunction1542881176278::getUtilityFunction(Plan* plan) {
    /*PROTECTED REGION ID(1542881176278) ENABLED START*/

    shared_ptr<UtilityFunction> defaultFunction = make_shared<DefaultUtilityFunction>(plan);
    return defaultFunction;

    /*PROTECTED REGION END*/
}

// State: Init in Plan: Master

/*
 *
 * Transition:
 *   - Name: MISSING_NAME, ConditionString: , Comment :
 *
 * Plans in State:
 *   - Plan - (Name): Go2RandomPositionDefault, (PlanID): 1542881996304
 *
 * Tasks:
 *   - DefaultTask (1542881176318) (Entrypoint: 1543227864154)
 *
 * States:
 *   - Init (1542881176280)
 *   - Move (1542881580237)
 *
 * Vars:
 */
bool TransitionCondition1542881647180::evaluate(shared_ptr<RunningPlan> rp) {
    /*PROTECTED REGION ID(1542881645594) ENABLED START*/
    return rp->isAnyChildStatus(PlanStatus::Success);
    /*PROTECTED REGION END*/
}

// State: Move in Plan: Master

/*
 *
 * Transition:
 *   - Name: MISSING_NAME, ConditionString: , Comment : Transition from Move to Init
 *
 * Plans in State:
 *   - Plan - (Name): Move, (PlanID): 1542882005838
 *
 * Tasks:
 *   - DefaultTask (1542881176318) (Entrypoint: 1543227864154)
 *
 * States:
 *   - Init (1542881176280)
 *   - Move (1542881580237)
 *
 * Vars:
 */
bool TransitionCondition1542881650423::evaluate(shared_ptr<RunningPlan> rp) {
    /*PROTECTED REGION ID(1542881648973) ENABLED START*/
    // transition happen if init flag is true in world model.
    return turtlesim::ALICATurtleWorldModel::get()->getInit();
    /*PROTECTED REGION END*/
}

}  // namespace alicaAutogenerated
