#include "Plans/constraints/BehaviourTriggerTestPlan1428508768572Constraints.h"
using namespace std;
using namespace alica;
/*PROTECTED REGION ID(ch1428508768572) ENABLED START*/
//Add additional using directives here
/*PROTECTED REGION END*/

namespace alicaAutogenerated
{
//Plan:BehaviourTriggerTestPlan

/*		
 * Tasks: 
 * - EP:1428508768574 : DefaultTask (1225112227903)
 *
 * States:
 * - NewState (1428508768573)
 *
 * Vars:
 */

// State: NewState

// State: NewState

}
