#include "Plans/constraints/MidFieldPlayPlan1402488770050Constraints.h"
using namespace std;
using namespace alica;
/*PROTECTED REGION ID(ch1402488770050) ENABLED START*/
//Add additional using directives here
/*PROTECTED REGION END*/

namespace alicaAutogenerated
{
//Plan:MidFieldPlayPlan

/*		
 * Tasks: 
 * - EP:1402488787819 : DefaultTask (1225112227903)
 * - EP:1402500828244 : DefaultTask (1225112227903)
 *
 * States:
 * - Wander (1402488787818)
 * - Tackle (1402489237914)
 * - Sync (1402489273401)
 * - Kill (1402500830885)
 * - Shoot (1402500833246)
 *
 * Vars:
 */

// State: Wander

// State: Wander

// State: Tackle

// State: Tackle

// State: Sync

// State: Sync

// State: Kill

// State: Kill

// State: Shoot

// State: Shoot

}
