#ifndef BackForthCONSTRAINT_H_
#define BackForth_H_
#include "engine/BasicConstraint.h"
#include <memory>

using namespace std;
using namespace alica;

namespace alica
{
class ProblemDescriptor;
class RunningPlan;
}

namespace alicaAutogenerated
{

} /* namespace alica */

#endif /* BackForthCONSTRAINT_H_ */
