#ifndef BehaviorSuccessSpamMasterCONSTRAINT_H_
#define BehaviorSuccessSpamMaster_H_
#include "engine/BasicConstraint.h"
#include <memory>

using namespace std;
using namespace alica;

namespace alica
{
    class ProblemDescriptor;
    class RunningPlan;
}

namespace alicaAutogenerated
{

} /* namespace alica */

#endif /* BehaviorSuccessSpamMasterCONSTRAINT_H_ */
