#ifndef FailsOnOneCONSTRAINT_H_
#define FailsOnOne_H_
#include "engine/BasicConstraint.h"
#include <memory>

using namespace std;
using namespace alica;

namespace alica
{
class ProblemDescriptor;
class RunningPlan;
}

namespace alicaAutogenerated
{

} /* namespace alica */

#endif /* FailsOnOneCONSTRAINT_H_ */
