#ifndef HandleFailExplicitCONSTRAINT_H_
#define HandleFailExplicit_H_
#include "engine/BasicConstraint.h"
#include <memory>

using namespace std;
using namespace alica;

namespace alica
{
class ProblemDescriptor;
class RunningPlan;
}

namespace alicaAutogenerated
{

} /* namespace alica */

#endif /* HandleFailExplicitCONSTRAINT_H_ */
