#ifndef OtherPlanCONSTRAINT_H_
#define OtherPlan_H_
#include "engine/BasicConstraint.h"
#include <memory>

using namespace std;
using namespace alica;

namespace alica
{
class ProblemDescriptor;
class RunningPlan;
} // namespace alica

namespace alicaAutogenerated
{
} // namespace alicaAutogenerated

#endif /* OtherPlanCONSTRAINT_H_ */
