#ifndef PreConditionPlanCONSTRAINT_H_
#define PreConditionPlan_H_
#include "engine/BasicConstraint.h"
#include <memory>

using namespace std;
using namespace alica;

namespace alica
{
    class ProblemDescriptor;
    class RunningPlan;
}

namespace alicaAutogenerated
{

} /* namespace alica */

#endif /* PreConditionPlanCONSTRAINT_H_ */
