#ifndef RuntimeConditionPlanCONSTRAINT_H_
#define RuntimeConditionPlan_H_
#include "engine/BasicConstraint.h"
#include <memory>

using namespace std;
using namespace alica;

namespace alica
{
    class ProblemDescriptor;
    class RunningPlan;
}

namespace alicaAutogenerated
{

} /* namespace alica */

#endif /* RuntimeConditionPlanCONSTRAINT_H_ */
