/*
 * IConstraintCreator.h
 *
 *  Created on: Oct 8, 2014
 *      Author: Stefan Jakob
 */

#pragma once

#include "engine/BasicConstraint.h"
#include <memory>

using std::make_shared;
using std::shared_ptr; // TODO: remove once autogenerated files have been reworked

namespace alica
{

class IConstraintCreator
{
public:
    virtual ~IConstraintCreator() {}
    virtual std::shared_ptr<BasicConstraint> createConstraint(int64_t constraintConfId) = 0;
};

} /* namespace alica */