package de.unikassel.vs.alica.planDesigner.modelmanagement;

public class Types {
    public static final String PLAN = "plan";
    public static final String MASTERPLAN = "masterplan";
    public static final String BEHAVIOUR = "behaviour";
    public static final String PLANTYPE = "plantype";
    public static final String TASKREPOSITORY = "taskrepository";
    public static final String TASK = "task";
    public static final String ROLESET = "roleset";
    public static final String ROLE = "role";
    public static final String ROLE_TASK_PROPERTY = "roletaskproperty";
    public static final String ROLE_CHARACTERISTIC = "rolecharacteristic";
    public static final String VARIABLE = "variable";
    public static final String FOLDER = "folder";
    public static final String ANNOTATEDPLAN = "annotatedplan";
    public static final String PRECONDITION = "precondition";
    public static final String QUANTIFIER = "quantifier";
    public static final String QUANTIFIER_FORALL = "all";
    public static final String RUNTIMECONDITION = "runtimecondition";
    public static final String POSTCONDITION = "postcondition";
    public static final String STATE = "state";
    public static final String INSTATE = "instate";
    public static final String OUTSTATE = "outstate";
    public static final String SUCCESSSTATE = "successstate";
    public static final String FAILURESTATE = "failurestate";
    public static final String INITSTATECONNECTION = "initstateconnection";
    public static final String TRANSITION = "transition";
    public static final String ENTRYPOINT = "entrypoint";
    public static final String SYNCHRONISATION = "synchronisation";
    public static final String SYNCTRANSITION = "synctransition";
    public static final String BENDPOINT = "bendpoint";
    public static final String ABSTRACTPLAN = "abstractplan";
    public static final String UIEXTENSION = "uiextension";
    public static final String UNSUPPORTED = "unsupported";
    public static final String VARIABLEBINDING = "variablebinding";
    public static final String CONFIGURATION = "configuration";
    public static final String CONF_ABSTRACTPLAN_WRAPPER = "configurationAbstractPlanWrapper";
    public static final String CONDITIONS = "conditions";
}
