#ifndef QueryPlan2_H_
#define QueryPlan2_H_

#include "DomainCondition.h"
#include "engine/BasicUtilityFunction.h"
#include "engine/UtilityFunction.h"
#include "engine/DefaultUtilityFunction.h"
/*PROTECTED REGION ID(incl1479718449392) ENABLED START*/
// Add inlcudes here
/*PROTECTED REGION END*/
using namespace alica;

namespace alicaAutogenerated {
/*PROTECTED REGION ID(meth1479718449392) ENABLED START*/
// Add other things here
/*PROTECTED REGION END*/
class UtilityFunction1479718449392 : public BasicUtilityFunction {
    shared_ptr<UtilityFunction> getUtilityFunction(Plan* plan);
};

}  // namespace alicaAutogenerated

#endif
