/*
 * CounterClass.h
 *
 *  Created on: Jul 14, 2015
 *      Author: cnpaul
 */

#ifndef ALICA_ALICA_TEST_AUTOGENERATED_SRC_COUNTERCLASS_H_
#define ALICA_ALICA_TEST_AUTOGENERATED_SRC_COUNTERCLASS_H_

namespace alicaAutogenerated {
class CounterClass {
public:
    CounterClass();
    virtual ~CounterClass();
    static int called;
};
}  // namespace alicaAutogenerated
#endif /* ALICA_ALICA_TEST_AUTOGENERATED_SRC_COUNTERCLASS_H_ */
