/*
 * DistBallRobot.h
 *
 *  Created on: Oct 27, 2014
 *      Author: Stefan Jakob
 */

#ifndef ALICA_ALICA_TEST_AUTOGENERATED_SRC_DISTBALLROBOT_H_
#define ALICA_ALICA_TEST_AUTOGENERATED_SRC_DISTBALLROBOT_H_

#include <engine/USummand.h>
#include <vector>
#include <string>
#include <memory>

namespace alica
{

	class UtilityInterval;
	class IAssignment;

	class DistBallRobot : public USummand
	{
	public:
		DistBallRobot(double weight, string name, long id, vector<long> relevantEntryPointIds);
		virtual ~DistBallRobot();
		void cacheEvalData ();
		UtilityInterval Eval(IAssignment* ass);


	protected:
		double weight;
		string name;
		long id;
		vector<long> relevantEntryPointIds;
		pair<double, double> sb;
		bool validAngle;
		double angleBallOpp;
		double velAngle;
	};

} /* namespace alica */

#endif /* ALICA_ALICA_TEST_AUTOGENERATED_SRC_DISTBALLROBOT_H_ */
