#include "Plans/AttackPlan1402488634525.h"
using namespace alica;
/*PROTECTED REGION ID(eph1402488634525) ENABLED START*/  // Add additional using directives here
/*PROTECTED REGION END*/
namespace alicaAutogenerated {
// Plan:AttackPlan

/* generated comment

 Task: DefaultTask  -> EntryPoint-ID: 1402488646221

 */
shared_ptr<UtilityFunction> UtilityFunction1402488634525::getUtilityFunction(Plan* plan) {
    /*PROTECTED REGION ID(1402488634525) ENABLED START*/

    shared_ptr<UtilityFunction> defaultFunction = make_shared<DefaultUtilityFunction>(plan);
    return defaultFunction;

    /*PROTECTED REGION END*/
}

// State: Attack in Plan: AttackPlan

/*
 *
 * Transition:
 *   - Name: MISSING_NAME, ConditionString: , Comment :
 *
 * Plans in State:
 *   - Plan - (Name): Tackle, (PlanID): 1402489318663
 *   - Plan - (Name): AttackOppDefault, (PlanID): 1402489366699
 *
 * Tasks:
 *   - DefaultTask (1225112227903) (Entrypoint: 1402488646221)
 *
 * States:
 *   - Attack (1402488646220)
 *   - Shoot (1402489396914)
 *
 * Vars:
 *	- ABC (1403772834750)
 *	- TestVar1 (1403772778288)
 */
bool TransitionCondition1402489460549::evaluate(shared_ptr<RunningPlan> rp) {
    /*PROTECTED REGION ID(1402489459382) ENABLED START*/
    return false;
    /*PROTECTED REGION END*/
}

// State: Shoot in Plan: AttackPlan

/*
 *
 * Transition:
 *   - Name: Condition-Name-Shoot-Attack, ConditionString: Some nice comment!, Comment :
 *
 * Plans in State:
 *   - Plan - (Name): AttackDefault, (PlanID): 1402488866727
 *
 * Tasks:
 *   - DefaultTask (1225112227903) (Entrypoint: 1402488646221)
 *
 * States:
 *   - Attack (1402488646220)
 *   - Shoot (1402489396914)
 *
 * Vars:
 *	- TestVar1 (1403772778288)
 *	- VarTest2 (1403772797469)
 *	- NewVar (1403772816953)
 *	- ABC (1403772834750)
 */
bool TransitionCondition1402489462088::evaluate(shared_ptr<RunningPlan> rp) {
    /*PROTECTED REGION ID(1402489460694) ENABLED START*/
    return false;
    /*PROTECTED REGION END*/
}

}  // namespace alicaAutogenerated
