#include "Plans/Defend1402488893641.h"
using namespace alica;
/*PROTECTED REGION ID(eph1402488893641) ENABLED START*/ // Add additional using directives here
/*PROTECTED REGION END*/
namespace alicaAutogenerated
{
// Plan:Defend

/* generated comment

 Task: DefaultTask  -> EntryPoint-ID: 1402488903550

 */
shared_ptr<UtilityFunction> UtilityFunction1402488893641::getUtilityFunction(Plan* plan)
{
    /*PROTECTED REGION ID(1402488893641) ENABLED START*/

    shared_ptr<UtilityFunction> defaultFunction = make_shared<DefaultUtilityFunction>(plan);
    return defaultFunction;

    /*PROTECTED REGION END*/
}

// State: Tackle in Plan: Defend

/*
 *
 * Transition:
 *   - Name: MISSING_NAME, ConditionString: , Comment : TackleToGetBall
 *
 * Plans in State:
 *   - Plan - (Name): TackleDefault, (PlanID): 1402488956661
 *   - Plan - (Name): Tackle, (PlanID): 1402489318663
 *
 * Tasks:
 *   - DefaultTask (1225112227903) (Entrypoint: 1402488903550)
 *
 * States:
 *   - Tackle (1402488903549)
 *   - GetGoal (1402488910751)
 *   - GetBall (1402488959965)
 *   - TryToDefendGoal (1402489037735)
 *
 * Vars:
 */
bool TransitionCondition1402488993122::evaluate(shared_ptr<RunningPlan> rp)
{
    /*PROTECTED REGION ID(1402488991762) ENABLED START*/
    return false;
    /*PROTECTED REGION END*/
}

// State: GetGoal in Plan: Defend

// State: GetBall in Plan: Defend

/*
 *
 * Transition:
 *   - Name: MISSING_NAME, ConditionString: , Comment : GetBallToTackle
 *
 * Plans in State:
 *
 * Tasks:
 *   - DefaultTask (1225112227903) (Entrypoint: 1402488903550)
 *
 * States:
 *   - Tackle (1402488903549)
 *   - GetGoal (1402488910751)
 *   - GetBall (1402488959965)
 *   - TryToDefendGoal (1402489037735)
 *
 * Vars:
 */
bool TransitionCondition1402488991641::evaluate(shared_ptr<RunningPlan> rp)
{
    /*PROTECTED REGION ID(1402488990761) ENABLED START*/
    return false;
    /*PROTECTED REGION END*/
}

/*
 *
 * Transition:
 *   - Name: MISSING_NAME, ConditionString: , Comment : TESTESTETS
 *
 * Plans in State:
 *
 * Tasks:
 *   - DefaultTask (1225112227903) (Entrypoint: 1402488903550)
 *
 * States:
 *   - Tackle (1402488903549)
 *   - GetGoal (1402488910751)
 *   - GetBall (1402488959965)
 *   - TryToDefendGoal (1402489037735)
 *
 * Vars:
 */
bool TransitionCondition1402489065962::evaluate(shared_ptr<RunningPlan> rp)
{
    /*PROTECTED REGION ID(1402489064693) ENABLED START*/
    return false;
    /*PROTECTED REGION END*/
}

// State: TryToDefendGoal in Plan: Defend

/*
 *
 * Transition:
 *   - Name: MISSING_NAME, ConditionString: , Comment : TryToDefendGoalToGetGoal
 *
 * Plans in State:
 *   - Plan - (Name): PlanType, (PlanID): 1402489564599
 *
 * Tasks:
 *   - DefaultTask (1225112227903) (Entrypoint: 1402488903550)
 *
 * States:
 *   - Tackle (1402488903549)
 *   - GetGoal (1402488910751)
 *   - GetBall (1402488959965)
 *   - TryToDefendGoal (1402489037735)
 *
 * Vars:
 */
bool TransitionCondition1402489073613::evaluate(shared_ptr<RunningPlan> rp)
{
    /*PROTECTED REGION ID(1402489071510) ENABLED START*/
    return false;
    /*PROTECTED REGION END*/
}

} // namespace alicaAutogenerated
