#include "Plans/HandleFailExplicit1530004915640.h"
using namespace alica;
/*PROTECTED REGION ID(eph1530004915640) ENABLED START*/ // Add additional using directives here
#include "SimpleSwitches.h"
/*PROTECTED REGION END*/
namespace alicaAutogenerated
{
// Plan:HandleFailExplicit

/* generated comment

 Task: DefaultTask  -> EntryPoint-ID: 1530004915642

 */
shared_ptr<UtilityFunction> UtilityFunction1530004915640::getUtilityFunction(Plan* plan)
{
    /*PROTECTED REGION ID(1530004915640) ENABLED START*/

    shared_ptr<UtilityFunction> defaultFunction = make_shared<DefaultUtilityFunction>(plan);
    return defaultFunction;

    /*PROTECTED REGION END*/
}

// State: A in Plan: HandleFailExplicit

/*
 *
 * Transition:
 *   - Name: MISSING_NAME, ConditionString: , Comment : From A to B, isset(0)
 *
 * Plans in State:
 *
 * Tasks:
 *   - DefaultTask (1225112227903) (Entrypoint: 1530004915642)
 *
 * States:
 *   - A (1530004915641)
 *   - B (1530004973591)
 *   - C (1530004975275)
 *   - D (1532424087894)
 *   - E (1532424097662)
 *
 * Vars:
 */
bool TransitionCondition1530004993493::evaluate(shared_ptr<RunningPlan> rp)
{
    /*PROTECTED REGION ID(1530004992551) ENABLED START*/
    return SimpleSwitches::isSet(0);
    /*PROTECTED REGION END*/
}

// State: B in Plan: HandleFailExplicit

/*
 *
 * Transition:
 *   - Name: MISSING_NAME, ConditionString: , Comment : AnyChildFail
 *
 * Plans in State:
 *   - Plan - (Name): FailsOnOne, (PlanID): 1530069246103
 *
 * Tasks:
 *   - DefaultTask (1225112227903) (Entrypoint: 1530004915642)
 *
 * States:
 *   - A (1530004915641)
 *   - B (1530004973591)
 *   - C (1530004975275)
 *   - D (1532424087894)
 *   - E (1532424097662)
 *
 * Vars:
 */
bool TransitionCondition1530004994611::evaluate(shared_ptr<RunningPlan> rp)
{
    /*PROTECTED REGION ID(1530004993680) ENABLED START*/
    return rp->isAnyChildStatus(PlanStatus::Failed);
    /*PROTECTED REGION END*/
}

// State: C in Plan: HandleFailExplicit

/*
 *
 * Transition:
 *   - Name: MISSING_NAME, ConditionString: , Comment : C to D, isset(2)
 *
 * Plans in State:
 *
 * Tasks:
 *   - DefaultTask (1225112227903) (Entrypoint: 1530004915642)
 *
 * States:
 *   - A (1530004915641)
 *   - B (1530004973591)
 *   - C (1530004975275)
 *   - D (1532424087894)
 *   - E (1532424097662)
 *
 * Vars:
 */
bool TransitionCondition1532424093178::evaluate(shared_ptr<RunningPlan> rp)
{
    /*PROTECTED REGION ID(1532424092280) ENABLED START*/
    return SimpleSwitches::isSet(2);
    /*PROTECTED REGION END*/
}

// State: D in Plan: HandleFailExplicit

/*
 *
 * Transition:
 *   - Name: MISSING_NAME, ConditionString: , Comment : AnyChildFail
 *
 * Plans in State:
 *   - Plan - (Name): AlwaysFailDefault, (PlanID): 1532424207423
 *
 * Tasks:
 *   - DefaultTask (1225112227903) (Entrypoint: 1530004915642)
 *
 * States:
 *   - A (1530004915641)
 *   - B (1530004973591)
 *   - C (1530004975275)
 *   - D (1532424087894)
 *   - E (1532424097662)
 *
 * Vars:
 */
bool TransitionCondition1532424113475::evaluate(shared_ptr<RunningPlan> rp)
{
    /*PROTECTED REGION ID(1532424112331) ENABLED START*/
    return rp->isAnyChildStatus(PlanStatus::Failed);
    /*PROTECTED REGION END*/
}

// State: E in Plan: HandleFailExplicit
}
