#include "Plans/HandleFailExplicitMaster1530004940652.h"
using namespace alica;
/*PROTECTED REGION ID(eph1530004940652) ENABLED START*/ // Add additional using directives here
/*PROTECTED REGION END*/
namespace alicaAutogenerated
{
// Plan:HandleFailExplicitMaster

/* generated comment

 Task: DefaultTask  -> EntryPoint-ID: 1530004940654

 */
shared_ptr<UtilityFunction> UtilityFunction1530004940652::getUtilityFunction(Plan* plan)
{
    /*PROTECTED REGION ID(1530004940652) ENABLED START*/

    shared_ptr<UtilityFunction> defaultFunction = make_shared<DefaultUtilityFunction>(plan);
    return defaultFunction;

    /*PROTECTED REGION END*/
}

// State: NewState in Plan: HandleFailExplicitMaster
}
