#include "Plans/MidFieldPlayPlan1402488770050.h"
using namespace alica;
/*PROTECTED REGION ID(eph1402488770050) ENABLED START*/ // Add additional using directives here
/*PROTECTED REGION END*/
namespace alicaAutogenerated
{
// Plan:MidFieldPlayPlan

// Check of RuntimeCondition - (Name): NewRuntimeCondition, (ConditionString): , (Comment) : Test RC

/*
 * Available Vars:
 */
bool RunTimeCondition1402489260911::evaluate(shared_ptr<RunningPlan> rp)
{
    /*PROTECTED REGION ID(1402489260911) ENABLED START*/
    return true;
    /*PROTECTED REGION END*/
}

/* generated comment

 Task: DefaultTask  -> EntryPoint-ID: 1402488787819

 Task: DefaultTask  -> EntryPoint-ID: 1402500828244

 */
shared_ptr<UtilityFunction> UtilityFunction1402488770050::getUtilityFunction(Plan* plan)
{
    /*PROTECTED REGION ID(1402488770050) ENABLED START*/

    shared_ptr<UtilityFunction> defaultFunction = make_shared<DefaultUtilityFunction>(plan);
    return defaultFunction;

    /*PROTECTED REGION END*/
}

// State: Wander in Plan: MidFieldPlayPlan

/*
 *
 * Transition:
 *   - Name: MISSING_NAME, ConditionString: , Comment :
 *
 * Plans in State:
 *   - Plan - (Name): NewBehaviourDefault, (PlanID): 1402488712657
 *
 * Tasks:
 *   - DefaultTask (1225112227903) (Entrypoint: 1402488787819)
 *   - DefaultTask (1225112227903) (Entrypoint: 1402500828244)
 *
 * States:
 *   - Wander (1402488787818)
 *   - Tackle (1402489237914)
 *   - Sync (1402489273401)
 *   - Kill (1402500830885)
 *   - Shoot (1402500833246)
 *
 * Vars:
 */
bool TransitionCondition1402489258509::evaluate(shared_ptr<RunningPlan> rp)
{
    /*PROTECTED REGION ID(1402489257607) ENABLED START*/
    return false;
    /*PROTECTED REGION END*/
}

/*
 *
 * Transition:
 *   - Name: MISSING_NAME, ConditionString: , Comment :
 *
 * Plans in State:
 *   - Plan - (Name): NewBehaviourDefault, (PlanID): 1402488712657
 *
 * Tasks:
 *   - DefaultTask (1225112227903) (Entrypoint: 1402488787819)
 *   - DefaultTask (1225112227903) (Entrypoint: 1402500828244)
 *
 * States:
 *   - Wander (1402488787818)
 *   - Tackle (1402489237914)
 *   - Sync (1402489273401)
 *   - Kill (1402500830885)
 *   - Shoot (1402500833246)
 *
 * Vars:
 */
bool TransitionCondition1402489278408::evaluate(shared_ptr<RunningPlan> rp)
{
    /*PROTECTED REGION ID(1402489276995) ENABLED START*/
    return false;
    /*PROTECTED REGION END*/
}

// State: Tackle in Plan: MidFieldPlayPlan

// State: Sync in Plan: MidFieldPlayPlan

// State: Kill in Plan: MidFieldPlayPlan

/*
 *
 * Transition:
 *   - Name: MISSING_NAME, ConditionString: , Comment :
 *
 * Plans in State:
 *   - Plan - (Name): TestPlanningProblem, (PlanID): 1403773823508
 *
 * Tasks:
 *   - DefaultTask (1225112227903) (Entrypoint: 1402488787819)
 *   - DefaultTask (1225112227903) (Entrypoint: 1402500828244)
 *
 * States:
 *   - Wander (1402488787818)
 *   - Tackle (1402489237914)
 *   - Sync (1402489273401)
 *   - Kill (1402500830885)
 *   - Shoot (1402500833246)
 *
 * Vars:
 */
bool TransitionCondition1402500844446::evaluate(shared_ptr<RunningPlan> rp)
{
    /*PROTECTED REGION ID(1402500843072) ENABLED START*/
    return false;
    /*PROTECTED REGION END*/
}

// State: Shoot in Plan: MidFieldPlayPlan

} // namespace alicaAutogenerated
