#include "Plans/PlanFour1407153683051.h"
using namespace alica;
/*PROTECTED REGION ID(eph1407153683051) ENABLED START*/  // Add additional using directives here
/*PROTECTED REGION END*/
namespace alicaAutogenerated {
// Plan:PlanFour

/* generated comment

 Task: DefaultTask  -> EntryPoint-ID: 1407153696703

 Task: AttackTask  -> EntryPoint-ID: 1407153949327

 */
shared_ptr<UtilityFunction> UtilityFunction1407153683051::getUtilityFunction(Plan* plan) {
    /*PROTECTED REGION ID(1407153683051) ENABLED START*/

    shared_ptr<UtilityFunction> defaultFunction = make_shared<DefaultUtilityFunction>(plan);
    return defaultFunction;

    /*PROTECTED REGION END*/
}

// State: DefaultState in Plan: PlanFour

// State: AttackState in Plan: PlanFour

}  // namespace alicaAutogenerated
