#include "Plans/PlanFive1407153703092.h"
using namespace alica;
/*PROTECTED REGION ID(eph1407153703092) ENABLED START*/ // Add additional using directives here
/*PROTECTED REGION END*/
namespace alicaAutogenerated
{
// Plan:PlanFive

/* generated comment

 Task: DefaultTask  -> EntryPoint-ID: 1407153717809

 Task: AttackTask  -> EntryPoint-ID: 1407153972059

 Task: DefendTask  -> EntryPoint-ID: 1407153973706

 Task: MidFieldTask  -> EntryPoint-ID: 1407153975075

 */
shared_ptr<UtilityFunction> UtilityFunction1407153703092::getUtilityFunction(Plan* plan)
{
    /*PROTECTED REGION ID(1407153703092) ENABLED START*/

    shared_ptr<UtilityFunction> defaultFunction = make_shared<DefaultUtilityFunction>(plan);
    return defaultFunction;

    /*PROTECTED REGION END*/
}

// State: DefaultState in Plan: PlanFive

// State: DefendState in Plan: PlanFive

// State: AttackState in Plan: PlanFive

// State: MidFieldState in Plan: PlanFive

} // namespace alicaAutogenerated
