#include "Plans/RealMasterPlanForSyncTest1418902217839.h"
using namespace alica;
/*PROTECTED REGION ID(eph1418902217839) ENABLED START*/  // Add additional using directives here
/*PROTECTED REGION END*/
namespace alicaAutogenerated {
// Plan:RealMasterPlanForSyncTest

/* generated comment

 Task: DefaultTask  -> EntryPoint-ID: 1418902217841

 */
shared_ptr<UtilityFunction> UtilityFunction1418902217839::getUtilityFunction(Plan* plan) {
    /*PROTECTED REGION ID(1418902217839) ENABLED START*/

    shared_ptr<UtilityFunction> defaultFunction = make_shared<DefaultUtilityFunction>(plan);
    return defaultFunction;

    /*PROTECTED REGION END*/
}

// State: NewState in Plan: RealMasterPlanForSyncTest

}  // namespace alicaAutogenerated
