#include "Plans/RuntimeConditionPlan1418042806575.h"
using namespace alica;
/*PROTECTED REGION ID(eph1418042806575) ENABLED START*/ // Add additional using directives here
#include "TestConstantValueSummand.h"
#include "TestWorldModel.h"
#include "engine/USummand.h"
#include <DistXContourTest.h>
/*PROTECTED REGION END*/
namespace alicaAutogenerated
{
// Plan:RuntimeConditionPlan

// Check of RuntimeCondition - (Name): NewRuntimeCondition, (ConditionString): , (Comment) :

/*
 * Available Vars:
 */
bool RunTimeCondition1418042967134::evaluate(shared_ptr<RunningPlan> rp)
{
    /*PROTECTED REGION ID(1418042967134) ENABLED START*/
    return alicaTests::TestWorldModel::getOne()->isRuntimeCondition1418042967134();
    /*PROTECTED REGION END*/
}

/* generated comment

 Task: DefaultTask  -> EntryPoint-ID: 1418042806577

 */
shared_ptr<UtilityFunction> UtilityFunction1418042806575::getUtilityFunction(Plan* plan)
{
    /*PROTECTED REGION ID(1418042806575) ENABLED START*/
    shared_ptr<UtilityFunction> function = make_shared<UtilityFunction>(0.5, 0.1, plan);
    function->editUtilSummands().emplace_back(new TestConstantValueSummand(0.5, 1.0));
    return function;
    /*PROTECTED REGION END*/
}

// State: RuntimeConditionTest in Plan: RuntimeConditionPlan

} // namespace alicaAutogenerated
