#include "Plans/Tackle1402489318663.h"
using namespace alica;
/*PROTECTED REGION ID(eph1402489318663) ENABLED START*/ //Add additional using directives here
/*PROTECTED REGION END*/
namespace alicaAutogenerated
{
//Plan:Tackle

/* generated comment
 
 Task: DefaultTask  -> EntryPoint-ID: 1402489329142

 */
shared_ptr<UtilityFunction> UtilityFunction1402489318663::getUtilityFunction(Plan* plan)
{
  /*PROTECTED REGION ID(1402489318663) ENABLED START*/

  shared_ptr < UtilityFunction > defaultFunction = make_shared < DefaultUtilityFunction > (plan);
  return defaultFunction;

  /*PROTECTED REGION END*/
}

//State: AttackOpp in Plan: Tackle

}
