#include "Plans/ProblemModule/QueryPlan21479718449392.h"
using namespace alica;
/*PROTECTED REGION ID(eph1479718449392) ENABLED START*/ //Add additional using directives here
/*PROTECTED REGION END*/
namespace alicaAutogenerated
{
    //Plan:QueryPlan2

    /* generated comment
     
     Task: DefaultTask  -> EntryPoint-ID: 1479718449394

     */
    shared_ptr<UtilityFunction> UtilityFunction1479718449392::getUtilityFunction(Plan* plan)
    {
        /*PROTECTED REGION ID(1479718449392) ENABLED START*/

        shared_ptr < UtilityFunction > defaultFunction = make_shared < DefaultUtilityFunction > (plan);
        return defaultFunction;

        /*PROTECTED REGION END*/
    }

//State: QueryState2 in Plan: QueryPlan2

}
