/*
 * CounterClass.cpp
 *
 *  Created on: Jul 14, 2015
 *      Author: cnpaul
 */

#include "CounterClass.h"
namespace alicaAutogenerated
{
std::atomic<int> CounterClass::called(0);
CounterClass::CounterClass() {}

CounterClass::~CounterClass() {}

} // namespace alicaAutogenerated
