#include "Plans/Authority/AuthorityTestMaster1414403396328.h"
using namespace alica;
/*PROTECTED REGION ID(eph1414403396328) ENABLED START*/ //Add additional using directives here
/*PROTECTED REGION END*/
namespace alicaAutogenerated
{
//Plan:AuthorityTestMaster

//Generation not implemented

/* generated comment
 
 Task: DefaultTask  -> EntryPoint-ID: 1414403396331

 */
shared_ptr<UtilityFunction> UtilityFunction1414403396328::getUtilityFunction(Plan* plan)
{
  /*PROTECTED REGION ID(1414403396328) ENABLED START*/

  shared_ptr < UtilityFunction > defaultFunction = make_shared < DefaultUtilityFunction > (plan);
  return defaultFunction;

  /*PROTECTED REGION END*/
}

//State: testState in Plan: AuthorityTestMaster

//Generation not implemented

//State: Init in Plan: AuthorityTestMaster

//Generation not implemented

}
