#include "ConstraintCreator.h"
#include <iostream>

#include "Plans/constraints/PlanOne1407153611768Constraints.h"

#include "Plans/constraints/FailsOnOne1530069246103Constraints.h"

#include "Plans/constraints/PlanFour1407153683051Constraints.h"

#include "Plans/constraints/RealMasterPlanForSyncTest1418902217839Constraints.h"

#include "Plans/constraints/Defend1402488893641Constraints.h"

#include "Plans/constraints/BackForth1529456584982Constraints.h"

#include "Plans/Authority/constraints/AuthorityTestMaster1414403396328Constraints.h"

#include "Plans/constraints/GoalPlan1402488870347Constraints.h"

#include "Plans/constraints/MasterPlan1402488437260Constraints.h"

#include "Plans/constraints/MasterPlanTestConditionPlanType1418042656594Constraints.h"

#include "Plans/constraints/AttackPlan1402488634525Constraints.h"

#include "Plans/constraints/PlanFive1407153703092Constraints.h"

#include "Plans/constraints/HandleFailExplicit1530004915640Constraints.h"

#include "Plans/Authority/constraints/AuthorityTest1414403413451Constraints.h"

#include "Plans/constraints/SimpleTestPlan1412252439925Constraints.h"

#include "Plans/constraints/RuntimeConditionPlan1418042806575Constraints.h"

#include "Plans/constraints/PlanThree1407153663917Constraints.h"

#include "Plans/constraints/MidFieldPlayPlan1402488770050Constraints.h"

#include "Plans/constraints/HandleFailExplicitMaster1530004940652Constraints.h"

#include "Plans/constraints/Tackle1402489318663Constraints.h"

#include "Plans/constraints/MasterSyncTransition1418825395939Constraints.h"

#include "Plans/constraints/MasterPlanTaskAssignment1407152758497Constraints.h"

#include "Plans/constraints/PlanTwo1407153645238Constraints.h"

#include "Plans/constraints/BehaviorSuccessSpamMaster1522377375148Constraints.h"

#include "Plans/constraints/MultiAgentTestPlan1413200862180Constraints.h"

#include "Plans/constraints/ConstraintTestPlan1414068524245Constraints.h"

#include "Plans/constraints/PreConditionPlan1418042796751Constraints.h"

#include "Plans/constraints/ConstraintTestMaster1414068495566Constraints.h"

#include "Plans/constraints/OtherPlan1418042819203Constraints.h"

#include "Plans/constraints/MultiAgentTestMaster1413200842973Constraints.h"

#include "Plans/constraints/BehaviourTriggerTestPlan1428508768572Constraints.h"

using namespace std;
using namespace alicaAutogenerated;

namespace alica
{

ConstraintCreator::ConstraintCreator() {}

ConstraintCreator::~ConstraintCreator() {}

shared_ptr<BasicConstraint> ConstraintCreator::createConstraint(long constraintConfId)
{
    switch (constraintConfId) {

    case 1403773741874:
        return make_shared<Constraint1403773741874>();
        break;

    case 1402489460549:
        return make_shared<Constraint1402489460549>();
        break;

    case 1402489462088:
        return make_shared<Constraint1402489462088>();
        break;

    case 1414068566297:
        return make_shared<Constraint1414068566297>();
        break;

    default:
        cerr << "ConstraintCreator: Unknown constraint requested: " << constraintConfId << endl;
        throw new exception();
        break;
    }
}
} // namespace alica
