#include "ConditionCreator.h"

#include "Plans/Move1542882005838.h"

#include "Plans/Master1542881176278.h"

using namespace alicaAutogenerated;
namespace alica {

ConditionCreator::ConditionCreator() {}
ConditionCreator::~ConditionCreator() {}

shared_ptr<BasicCondition> ConditionCreator::createConditions(long conditionConfId) {
    switch (conditionConfId) {
        case 1543284793605:

            return make_shared<RunTimeCondition1543284793605>();

            break;

        case 1542881647180:

            return make_shared<TransitionCondition1542881647180>();

            break;

        case 1542881650423:

            return make_shared<TransitionCondition1542881650423>();

            break;

        default:
            cerr << "ConditionCreator: Unknown condition id requested: " << conditionConfId << endl;
            throw new exception();
            break;
    }
}
}  // namespace alica
