#include "ConstraintCreator.h"
#include <iostream>

#include "Plans/constraints/Move1542882005838Constraints.h"

#include "Plans/constraints/Master1542881176278Constraints.h"

using namespace std;
using namespace alicaAutogenerated;

namespace alica {

ConstraintCreator::ConstraintCreator() {}

ConstraintCreator::~ConstraintCreator() {}

shared_ptr<BasicConstraint> ConstraintCreator::createConstraint(long constraintConfId) {
    switch (constraintConfId) {
        case 1543284793605:
            return make_shared<Constraint1543284793605>();
            break;

        default:
            cerr << "ConstraintCreator: Unknown constraint requested: " << constraintConfId << endl;
            throw new exception();
            break;
    }
}

}  // namespace alica
