#include <iostream>
#include "UtilityFunctionCreator.h"

#include "Plans/Move1542882005838.h"

#include "Plans/Master1542881176278.h"

using namespace std;
using namespace alicaAutogenerated;
namespace alica {

UtilityFunctionCreator::~UtilityFunctionCreator() {}

UtilityFunctionCreator::UtilityFunctionCreator() {}

shared_ptr<BasicUtilityFunction> UtilityFunctionCreator::createUtility(long utilityfunctionConfId) {
    switch (utilityfunctionConfId) {
        case 1542882005838:
            return make_shared<UtilityFunction1542882005838>();
            break;

        case 1542881176278:
            return make_shared<UtilityFunction1542881176278>();
            break;

        default:
            cerr << "UtilityFunctionCreator: Unknown utility requested: " << utilityfunctionConfId << endl;
            throw new exception();
            break;
    }
}

}  // namespace alica
