#include "Plans/Authority/constraints/AuthorityTest1414403413451Constraints.h"
using namespace std;
using namespace alica;
/*PROTECTED REGION ID(ch1414403413451) ENABLED START*/
// Add additional using directives here
/*PROTECTED REGION END*/

namespace alicaAutogenerated
{
// Plan:AuthorityTest

/*
 * Tasks:
 * - EP:1414403429951 : DefaultTask (1225112227903)
 * - EP:1414403522424 : AttackTask (1407153522080)
 *
 * States:
 * - UpperState (1414403429950)
 * - LowerState (1414403553717)
 *
 * Vars:
 */

// State: UpperState

// State: UpperState

// State: LowerState

// State: LowerState

} // namespace alicaAutogenerated
