#include "Plans/ProblemModule/ProbBuildingLevel1_11479557664989.h"
using namespace alica;
/*PROTECTED REGION ID(eph1479557664989) ENABLED START*/ // Add additional using directives here
/*PROTECTED REGION END*/
namespace alicaAutogenerated
{
// Plan:ProbBuildingLevel1_1

/* generated comment

 Task: DefaultTask  -> EntryPoint-ID: 1479557690963

 */
shared_ptr<UtilityFunction> UtilityFunction1479557664989::getUtilityFunction(Plan* plan)
{
    /*PROTECTED REGION ID(1479557664989) ENABLED START*/

    shared_ptr<UtilityFunction> defaultFunction = make_shared<DefaultUtilityFunction>(plan);
    return defaultFunction;

    /*PROTECTED REGION END*/
}

// State: MiddleState in Plan: ProbBuildingLevel1_1

} // namespace alicaAutogenerated
