#include "Plans/BehaviourTriggerTestPlan1428508768572.h"
using namespace alica;
/*PROTECTED REGION ID(eph1428508768572) ENABLED START*/ //Add additional using directives here
/*PROTECTED REGION END*/
namespace alicaAutogenerated
{
    //Plan:BehaviourTriggerTestPlan

    /* generated comment
     
     Task: DefaultTask  -> EntryPoint-ID: 1428508768574

     */
    shared_ptr<UtilityFunction> UtilityFunction1428508768572::getUtilityFunction(Plan* plan)
    {
        /*PROTECTED REGION ID(1428508768572) ENABLED START*/

        shared_ptr < UtilityFunction > defaultFunction = make_shared < DefaultUtilityFunction > (plan);
        return defaultFunction;

        /*PROTECTED REGION END*/
    }

//State: NewState in Plan: BehaviourTriggerTestPlan

}
