#include "Plans/GoalPlan1402488870347.h"
using namespace alica;
/*PROTECTED REGION ID(eph1402488870347) ENABLED START*/  // Add additional using directives here
/*PROTECTED REGION END*/
namespace alicaAutogenerated {
// Plan:GoalPlan

// Check of RuntimeCondition - (Name): NewRuntimeCondition, (ConditionString): test, (Comment) :

/*
 * Available Vars:
 *	- test (1403773747758)
 */
bool RunTimeCondition1403773741874::evaluate(shared_ptr<RunningPlan> rp) {
    /*PROTECTED REGION ID(1403773741874) ENABLED START*/
    return true;
    /*PROTECTED REGION END*/
}

// Check of PreCondition - (Name): PreCondition, (ConditionString):  , (Comment) : Test PC

/*
 * Available Vars:
 */
bool PreCondition1402489131988::evaluate(shared_ptr<RunningPlan> rp) {
    /*PROTECTED REGION ID(1402489131988) ENABLED START*/
    //--> "PreCondition:1402489131988  not implemented";
    return true;
    /*PROTECTED REGION END*/
}

/* generated comment

 Task: DefaultTask  -> EntryPoint-ID: 1402488881800

 */
shared_ptr<UtilityFunction> UtilityFunction1402488870347::getUtilityFunction(Plan* plan) {
    /*PROTECTED REGION ID(1402488870347) ENABLED START*/

    shared_ptr<UtilityFunction> defaultFunction = make_shared<DefaultUtilityFunction>(plan);
    return defaultFunction;

    /*PROTECTED REGION END*/
}

// State: Shoot in Plan: GoalPlan

/*
 *
 * Transition:
 *   - Name: MISSING_NAME, ConditionString: , Comment :
 *
 * Plans in State:
 *
 * Tasks:
 *   - DefaultTask (1225112227903) (Entrypoint: 1402488881800)
 *
 * States:
 *   - Shoot (1402488881799)
 *   - Miss (1402489152217)
 *   - Scored (1402489192198)
 *
 * Vars:
 */
bool TransitionCondition1402489174338::evaluate(shared_ptr<RunningPlan> rp) {
    /*PROTECTED REGION ID(1402489173167) ENABLED START*/
    return false;
    /*PROTECTED REGION END*/
}

// State: Miss in Plan: GoalPlan

/*
 *
 * Transition:
 *   - Name: MISSING_NAME, ConditionString: , Comment :
 *
 * Plans in State:
 *
 * Tasks:
 *   - DefaultTask (1225112227903) (Entrypoint: 1402488881800)
 *
 * States:
 *   - Shoot (1402488881799)
 *   - Miss (1402489152217)
 *   - Scored (1402489192198)
 *
 * Vars:
 */
bool TransitionCondition1402489206278::evaluate(shared_ptr<RunningPlan> rp) {
    /*PROTECTED REGION ID(1402489205153) ENABLED START*/
    return false;
    /*PROTECTED REGION END*/
}

/*
 *
 * Transition:
 *   - Name: MISSING_NAME, ConditionString: , Comment :
 *
 * Plans in State:
 *
 * Tasks:
 *   - DefaultTask (1225112227903) (Entrypoint: 1402488881800)
 *
 * States:
 *   - Shoot (1402488881799)
 *   - Miss (1402489152217)
 *   - Scored (1402489192198)
 *
 * Vars:
 */
bool TransitionCondition1402489218027::evaluate(shared_ptr<RunningPlan> rp) {
    /*PROTECTED REGION ID(1402489216617) ENABLED START*/
    return false;
    /*PROTECTED REGION END*/
}

// State: Scored in Plan: GoalPlan

}  // namespace alicaAutogenerated
