#include "Plans/MultiAgentTestMaster1413200842973.h"
using namespace alica;
/*PROTECTED REGION ID(eph1413200842973) ENABLED START*/ //Add additional using directives here
/*PROTECTED REGION END*/
namespace alicaAutogenerated
{
//Plan:MultiAgentTestMaster

/* generated comment
 
 Task: DefaultTask  -> EntryPoint-ID: 1413200842975

 */
shared_ptr<UtilityFunction> UtilityFunction1413200842973::getUtilityFunction(Plan* plan)
{
  /*PROTECTED REGION ID(1413200842973) ENABLED START*/

  shared_ptr < UtilityFunction > defaultFunction = make_shared < DefaultUtilityFunction > (plan);
  return defaultFunction;

  /*PROTECTED REGION END*/
}

//State: Init in Plan: MultiAgentTestMaster

/*
 *		
 * Transition:
 *   - Name: , ConditionString: , Comment :  
 *
 * Plans in State: 
 *
 * Tasks: 
 *   - DefaultTask (1225112227903) (Entrypoint: 1413200842975)
 *
 * States:
 *   - Init (1413200842974)
 *   - Start (1413201213955)
 *   - Finished (1413201380359)
 *
 * Vars:
 */
bool TransitionCondition1413201227586::evaluate(shared_ptr<RunningPlan> rp)
{
  /*PROTECTED REGION ID(1413201226246) ENABLED START*/
  return false;
  /*PROTECTED REGION END*/

}

//State: Start in Plan: MultiAgentTestMaster

/*
 *		
 * Transition:
 *   - Name: , ConditionString: , Comment :  
 *
 * Plans in State: 				
 *   - Plan - (Name): MultiAgentTestPlan, (PlanID): 1413200862180 
 *
 * Tasks: 
 *   - DefaultTask (1225112227903) (Entrypoint: 1413200842975)
 *
 * States:
 *   - Init (1413200842974)
 *   - Start (1413201213955)
 *   - Finished (1413201380359)
 *
 * Vars:
 */
bool TransitionCondition1413201389955::evaluate(shared_ptr<RunningPlan> rp)
{
  /*PROTECTED REGION ID(1413201388722) ENABLED START*/
  return false;
  /*PROTECTED REGION END*/

}

//State: Finished in Plan: MultiAgentTestMaster

}
