#include "Plans/OtherPlan1418042819203.h"
using namespace alica;
/*PROTECTED REGION ID(eph1418042819203) ENABLED START*/ //Add additional using directives here
#include "DistXContour.h"
#include "engine/USummand.h"
#include "TestConstantValueSummand.h"
/*PROTECTED REGION END*/
namespace alicaAutogenerated {
//Plan:OtherPlan

/* generated comment

 Task: DefaultTask  -> EntryPoint-ID: 1418042819206

 */
	shared_ptr<UtilityFunction> UtilityFunction1418042819203::getUtilityFunction(
			Plan* plan) {
		/*PROTECTED REGION ID(1418042819203) ENABLED START*/

		TestConstantValueSummand* us = new TestConstantValueSummand(0.5, "OtherPlan", 1, 0.2);
		list<USummand*> utilSummands;
		utilSummands.push_back(us);
		shared_ptr<UtilityFunction> function = make_shared<UtilityFunction>("OtherPlanUtilTest", utilSummands, 0.5, 0.1, plan);
		return function;
		/*PROTECTED REGION END*/
	}

//State: OtherPlanTest in Plan: OtherPlan

}
