#include "Plans/PlanTwo1407153645238.h"
using namespace alica;
/*PROTECTED REGION ID(eph1407153645238) ENABLED START*/ //Add additional using directives here
/*PROTECTED REGION END*/
namespace alicaAutogenerated
{
//Plan:PlanTwo

/* generated comment
 
 Task: DefaultTask  -> EntryPoint-ID: 1407153656782

 Task: AttackTask  -> EntryPoint-ID: 1407153821287

 Task: DefendTask  -> EntryPoint-ID: 1407153842648

 */
shared_ptr<UtilityFunction> UtilityFunction1407153645238::getUtilityFunction(Plan* plan)
{
  /*PROTECTED REGION ID(1407153645238) ENABLED START*/

  shared_ptr < UtilityFunction > defaultFunction = make_shared < DefaultUtilityFunction > (plan);
  return defaultFunction;

  /*PROTECTED REGION END*/
}

//State: DefaultState in Plan: PlanTwo

//State: AttackState in Plan: PlanTwo

//State: DefendState in Plan: PlanTwo

}
