#include "Plans/PlanThree1407153663917.h"
using namespace alica;
/*PROTECTED REGION ID(eph1407153663917) ENABLED START*/  // Add additional using directives here
/*PROTECTED REGION END*/
namespace alicaAutogenerated {
// Plan:PlanThree

/* generated comment

 Task: DefaultTask  -> EntryPoint-ID: 1407153675525

 Task: MidFieldTask  -> EntryPoint-ID: 1407153896585

 Task: DefendTask  -> EntryPoint-ID: 1407153899241

 */
shared_ptr<UtilityFunction> UtilityFunction1407153663917::getUtilityFunction(Plan* plan) {
    /*PROTECTED REGION ID(1407153663917) ENABLED START*/

    shared_ptr<UtilityFunction> defaultFunction = make_shared<DefaultUtilityFunction>(plan);
    return defaultFunction;

    /*PROTECTED REGION END*/
}

// State: DefaultState in Plan: PlanThree

// State: MidFieldState in Plan: PlanThree

// State: DefendState in Plan: PlanThree

}  // namespace alicaAutogenerated
