#include "Plans/constraints/BackForth1529456584982Constraints.h"
using namespace std;
using namespace alica;
/*PROTECTED REGION ID(ch1529456584982) ENABLED START*/
// Add additional using directives here
/*PROTECTED REGION END*/

namespace alicaAutogenerated
{
// Plan:BackForth

/*
 * Tasks:
 * - EP:1529456584984 : DefaultTask (1225112227903)
 *
 * States:
 * - First (1529456584983)
 * - Second (1529456591410)
 *
 * Vars:
 */

// State: First

// State: First

// State: Second

// State: Second
} // namespace alicaAutogenerated
