#include "Plans/constraints/BehaviorSuccessSpamMaster1522377375148Constraints.h"
using namespace std;
using namespace alica;
/*PROTECTED REGION ID(ch1522377375148) ENABLED START*/
//Add additional using directives here
/*PROTECTED REGION END*/

namespace alicaAutogenerated
{
//Plan:BehaviorSuccessSpamMaster

/*		
 * Tasks: 
 * - EP:1522377375150 : DefaultTask (1225112227903)
 *
 * States:
 * - Normal (1522377375149)
 * - Dummy (1522377929290)
 *
 * Vars:
 */

// State: Normal

// State: Normal

// State: Dummy

// State: Dummy

}
