#include "Plans/constraints/Defend1402488893641Constraints.h"
using namespace std;
using namespace alica;
/*PROTECTED REGION ID(ch1402488893641) ENABLED START*/
//Add additional using directives here
/*PROTECTED REGION END*/

namespace alicaAutogenerated
{
//Plan:Defend

/*		
 * Tasks: 
 * - EP:1402488903550 : DefaultTask (1225112227903)
 *
 * States:
 * - Tackle (1402488903549)
 * - GetGoal (1402488910751)
 * - GetBall (1402488959965)
 * - TryToDefendGoal (1402489037735)
 *
 * Vars:
 */

// State: Tackle

// State: Tackle

// State: GetGoal

// State: GetGoal

// State: GetBall

// State: GetBall

// State: TryToDefendGoal

// State: TryToDefendGoal

}
