#include "Plans/constraints/GoalPlan1402488870347Constraints.h"
using namespace std;
using namespace alica;
/*PROTECTED REGION ID(ch1402488870347) ENABLED START*/
// Add additional using directives here
/*PROTECTED REGION END*/

namespace alicaAutogenerated {
// Plan:GoalPlan

/*
 * Tasks:
 * - EP:1402488881800 : DefaultTask (1225112227903)
 *
 * States:
 * - Shoot (1402488881799)
 * - Miss (1402489152217)
 * - Scored (1402489192198)
 *
 * Vars:
 * - test (1403773747758)
 */

/*
 * RuntimeCondition - (Name): NewRuntimeCondition
 * (ConditionString): test
 * Static Variables: [test]
 * Domain Variables:

 * forall agents in Miss let v = [test]

 */
void Constraint1403773741874::getConstraint(shared_ptr<ProblemDescriptor> c, shared_ptr<RunningPlan>) {
    /*PROTECTED REGION ID(cc1403773741874) ENABLED START*/
    // Proteced
    /*PROTECTED REGION END*/
}

// State: Shoot

// State: Shoot

// State: Miss

// State: Miss

// State: Scored

// State: Scored

}  // namespace alicaAutogenerated
