#include "Plans/constraints/HandleFailExplicitMaster1530004940652Constraints.h"
using namespace std;
using namespace alica;
/*PROTECTED REGION ID(ch1530004940652) ENABLED START*/
// Add additional using directives here
/*PROTECTED REGION END*/

namespace alicaAutogenerated
{
// Plan:HandleFailExplicitMaster

/*
 * Tasks:
 * - EP:1530004940654 : DefaultTask (1225112227903)
 *
 * States:
 * - NewState (1530004940653)
 *
 * Vars:
 */

// State: NewState

// State: NewState
}
