#include "Plans/constraints/HandleFailExplicit1530004915640Constraints.h"
using namespace std;
using namespace alica;
/*PROTECTED REGION ID(ch1530004915640) ENABLED START*/
// Add additional using directives here
/*PROTECTED REGION END*/

namespace alicaAutogenerated
{
// Plan:HandleFailExplicit

/*
 * Tasks:
 * - EP:1530004915642 : DefaultTask (1225112227903)
 *
 * States:
 * - A (1530004915641)
 * - B (1530004973591)
 * - C (1530004975275)
 *
 * Vars:
 */

// State: A

// State: A

// State: B

// State: B

// State: C

// State: C
}
