#include "Plans/constraints/MasterPlanTestConditionPlanType1418042656594Constraints.h"
using namespace std;
using namespace alica;
/*PROTECTED REGION ID(ch1418042656594) ENABLED START*/
//Add additional using directives here
/*PROTECTED REGION END*/

namespace alicaAutogenerated
{
//Plan:MasterPlanTestConditionPlanType

/*		
 * Tasks: 
 * - EP:1418042656596 : DefaultTask (1225112227903)
 *
 * States:
 * - Start (1418042656595)
 * - Plantype (1418042674811)
 *
 * Vars:
 */

// State: Start

// State: Start

// State: Plantype

// State: Plantype

}
