#include "Plans/constraints/MasterPlan1402488437260Constraints.h"
using namespace std;
using namespace alica;
/*PROTECTED REGION ID(ch1402488437260) ENABLED START*/
// Add additional using directives here
/*PROTECTED REGION END*/

namespace alicaAutogenerated {
// Plan:MasterPlan

/*
 * Tasks:
 * - EP:1402488437263 : DefaultTask (1225112227903)
 *
 * States:
 * - Attack (1402488437261)
 * - Defend (1402488463437)
 * - Goal (1402488470615)
 * - MidField (1402488477650)
 * - SucGoalState (1402488536570)
 *
 * Vars:
 */

// State: Attack

// State: Attack

// State: Defend

// State: Defend

// State: Goal

// State: Goal

// State: MidField

// State: MidField

// State: SucGoalState

// State: SucGoalState

}  // namespace alicaAutogenerated
