#include "Plans/constraints/MasterSyncTransition1418825395939Constraints.h"
using namespace std;
using namespace alica;
/*PROTECTED REGION ID(ch1418825395939) ENABLED START*/
// Add additional using directives here
/*PROTECTED REGION END*/

namespace alicaAutogenerated {
// Plan:MasterSyncTransition

/*
 * Tasks:
 * - EP:1418825395941 : AttackTask (1407153522080)
 * - EP:1418825402617 : DefaultTask (1225112227903)
 *
 * States:
 * - FirstTaskFirstState (1418825395940)
 * - SecondTaskFirstState (1418825404963)
 * - FirstTaskSecondState (1418825409988)
 * - SecondTaskSecondState (1418825411686)
 *
 * Vars:
 */

// State: FirstTaskFirstState

// State: FirstTaskFirstState

// State: SecondTaskFirstState

// State: SecondTaskFirstState

// State: FirstTaskSecondState

// State: FirstTaskSecondState

// State: SecondTaskSecondState

// State: SecondTaskSecondState

}  // namespace alicaAutogenerated
