#include "Plans/constraints/MultiAgentTestMaster1413200842973Constraints.h"
using namespace std;
using namespace alica;
/*PROTECTED REGION ID(ch1413200842973) ENABLED START*/
// Add additional using directives here
/*PROTECTED REGION END*/

namespace alicaAutogenerated {
// Plan:MultiAgentTestMaster

/*
 * Tasks:
 * - EP:1413200842975 : DefaultTask (1225112227903)
 *
 * States:
 * - Init (1413200842974)
 * - Start (1413201213955)
 * - Finished (1413201380359)
 *
 * Vars:
 */

// State: Init

// State: Init

// State: Start

// State: Start

// State: Finished

// State: Finished

}  // namespace alicaAutogenerated
