#include "Plans/constraints/OtherPlan1418042819203Constraints.h"
using namespace std;
using namespace alica;
/*PROTECTED REGION ID(ch1418042819203) ENABLED START*/
//Add additional using directives here
/*PROTECTED REGION END*/

namespace alicaAutogenerated
{
//Plan:OtherPlan

/*		
 * Tasks: 
 * - EP:1418042819206 : DefaultTask (1225112227903)
 *
 * States:
 * - OtherPlanTest (1418042819204)
 *
 * Vars:
 */

// State: OtherPlanTest

// State: OtherPlanTest

}
