#include "Plans/constraints/PlanTwo1407153645238Constraints.h"
using namespace std;
using namespace alica;
/*PROTECTED REGION ID(ch1407153645238) ENABLED START*/
// Add additional using directives here
/*PROTECTED REGION END*/

namespace alicaAutogenerated
{
// Plan:PlanTwo

/*
 * Tasks:
 * - EP:1407153656782 : DefaultTask (1225112227903)
 * - EP:1407153821287 : AttackTask (1407153522080)
 * - EP:1407153842648 : DefendTask (1402488486725)
 *
 * States:
 * - DefaultState (1407153656781)
 * - AttackState (1407153860891)
 * - DefendState (1407153869754)
 *
 * Vars:
 */

// State: DefaultState

// State: DefaultState

// State: AttackState

// State: AttackState

// State: DefendState

// State: DefendState

} // namespace alicaAutogenerated
