#include "Plans/constraints/PlanOne1407153611768Constraints.h"
using namespace std;
using namespace alica;
/*PROTECTED REGION ID(ch1407153611768) ENABLED START*/
// Add additional using directives here
/*PROTECTED REGION END*/

namespace alicaAutogenerated {
// Plan:PlanOne

/*
 * Tasks:
 * - EP:1407153636262 : DefaultTask (1225112227903)
 * - EP:1407153791141 : AttackTask (1407153522080)
 *
 * States:
 * - DefaultState (1407153636261)
 * - AttackState (1407153807487)
 *
 * Vars:
 */

// State: DefaultState

// State: DefaultState

// State: AttackState

// State: AttackState

}  // namespace alicaAutogenerated
