#include "Plans/constraints/PlanFive1407153703092Constraints.h"
using namespace std;
using namespace alica;
/*PROTECTED REGION ID(ch1407153703092) ENABLED START*/
// Add additional using directives here
/*PROTECTED REGION END*/

namespace alicaAutogenerated
{
// Plan:PlanFive

/*
 * Tasks:
 * - EP:1407153717809 : DefaultTask (1225112227903)
 * - EP:1407153972059 : AttackTask (1407153522080)
 * - EP:1407153973706 : DefendTask (1402488486725)
 * - EP:1407153975075 : MidFieldTask (1407153536219)
 *
 * States:
 * - DefaultState (1407153717808)
 * - DefendState (1407153985762)
 * - AttackState (1407153987910)
 * - MidFieldState (1407153989550)
 *
 * Vars:
 */

// State: DefaultState

// State: DefaultState

// State: DefendState

// State: DefendState

// State: AttackState

// State: AttackState

// State: MidFieldState

// State: MidFieldState

} // namespace alicaAutogenerated
