#include "Plans/constraints/PlanFour1407153683051Constraints.h"
using namespace std;
using namespace alica;
/*PROTECTED REGION ID(ch1407153683051) ENABLED START*/
// Add additional using directives here
/*PROTECTED REGION END*/

namespace alicaAutogenerated {
// Plan:PlanFour

/*
 * Tasks:
 * - EP:1407153696703 : DefaultTask (1225112227903)
 * - EP:1407153949327 : AttackTask (1407153522080)
 *
 * States:
 * - DefaultState (1407153696702)
 * - AttackState (1407153959299)
 *
 * Vars:
 */

// State: DefaultState

// State: DefaultState

// State: AttackState

// State: AttackState

}  // namespace alicaAutogenerated
