#include "Plans/constraints/RealMasterPlanForSyncTest1418902217839Constraints.h"
using namespace std;
using namespace alica;
/*PROTECTED REGION ID(ch1418902217839) ENABLED START*/
// Add additional using directives here
/*PROTECTED REGION END*/

namespace alicaAutogenerated {
// Plan:RealMasterPlanForSyncTest

/*
 * Tasks:
 * - EP:1418902217841 : DefaultTask (1225112227903)
 *
 * States:
 * - NewState (1418902217840)
 *
 * Vars:
 */

// State: NewState

// State: NewState

}  // namespace alicaAutogenerated
