#include "Plans/constraints/SimpleTestPlan1412252439925Constraints.h"
using namespace std;
using namespace alica;
/*PROTECTED REGION ID(ch1412252439925) ENABLED START*/
// Add additional using directives here
/*PROTECTED REGION END*/

namespace alicaAutogenerated {
// Plan:SimpleTestPlan

/*
 * Tasks:
 * - EP:1412252439927 : DefaultTask (1225112227903)
 *
 * States:
 * - TestState1 (1412252439926)
 * - TestState2 (1412761855746)
 *
 * Vars:
 */

// State: TestState1

// State: TestState1

// State: TestState2

// State: TestState2

}  // namespace alicaAutogenerated
