#include "Plans/constraints/Tackle1402489318663Constraints.h"
using namespace std;
using namespace alica;
/*PROTECTED REGION ID(ch1402489318663) ENABLED START*/
// Add additional using directives here
/*PROTECTED REGION END*/

namespace alicaAutogenerated
{
// Plan:Tackle

/*
 * Tasks:
 * - EP:1402489329142 : DefaultTask (1225112227903)
 *
 * States:
 * - AttackOpp (1402489329141)
 *
 * Vars:
 */

// State: AttackOpp

// State: AttackOpp

} // namespace alicaAutogenerated
