#include "Plans/constraints/BehaviourTriggerPlan1428492704177Constraints.h"
using namespace std;
using namespace alica;
/*PROTECTED REGION ID(ch1428492704177) ENABLED START*/
// Add additional using directives here
/*PROTECTED REGION END*/

namespace alicaAutogenerated
{
// Plan:BehaviourTriggerPlan

/*
 * Tasks:
 * - EP:1428492704179 : DefaultTask (1225112227903)
 *
 * States:
 * - TestState1 (1428492704178)
 *
 * Vars:
 */

// State: TestState1

// State: TestState1

} // namespace alicaAutogenerated
