#include "Plans/constraints/ConstraintTestPlan1414068524245Constraints.h"
using namespace std;
using namespace alica;
/*PROTECTED REGION ID(ch1414068524245) ENABLED START*/
#include "CounterClass.h"
#include <iostream>
// Add additional using directives here
/*PROTECTED REGION END*/

namespace alicaAutogenerated
{
// Plan:ConstraintTestPlan

/*
 * Tasks:
 * - EP:1414068524247 : DefaultTask (1225112227903)
 *
 * States:
 * - constraintRunner (1414068524246)
 *
 * Vars:
 * - X (1414068572540)
 * - Y (1414068576620)
 */

/*
 * RuntimeCondition - (Name): NewRuntimeCondition
 * (ConditionString):
 * Static Variables: [X, Y]
 * Domain Variables:

 */
void Constraint1414068566297::getConstraint(shared_ptr<ProblemDescriptor> c, shared_ptr<RunningPlan>)
{
    /*PROTECTED REGION ID(cc1414068566297) ENABLED START*/
    // Proteced
    cout << "#########################################" << endl;
    CounterClass::called++;
    /*PROTECTED REGION END*/
}

// State: constraintRunner

// State: constraintRunner

} // namespace alicaAutogenerated
