#ifndef ProblemBuildingMasterCONSTRAINT_H_
#define ProblemBuildingMaster_H_
#include "engine/BasicConstraint.h"
#include <memory>

using namespace std;
using namespace alica;

namespace alica {
class ProblemDescriptor;
class RunningPlan;
}  // namespace alica

namespace alicaAutogenerated {

class Constraint1479557592662 : public BasicConstraint {
    void getConstraint(shared_ptr<ProblemDescriptor> c, shared_ptr<RunningPlan> rp);
};

}  // namespace alicaAutogenerated

#endif /* ProblemBuildingMasterCONSTRAINT_H_ */
