#ifndef QueryPlan2CONSTRAINT_H_
#define QueryPlan2_H_
#include "engine/BasicConstraint.h"
#include <memory>

using namespace std;
using namespace alica;

namespace alica
{
    class ProblemDescriptor;
    class RunningPlan;
}

namespace alicaAutogenerated
{

} /* namespace alica */

#endif /* QueryPlan2CONSTRAINT_H_ */
