#ifndef QueryPlan1CONSTRAINT_H_
#define QueryPlan1_H_
#include "engine/BasicConstraint.h"
#include <memory>

using namespace std;
using namespace alica;

namespace alica {
class ProblemDescriptor;
class RunningPlan;
}  // namespace alica

namespace alicaAutogenerated {

class Constraint1479556084493 : public BasicConstraint {
    void getConstraint(shared_ptr<ProblemDescriptor> c, shared_ptr<RunningPlan> rp);
};

}  // namespace alicaAutogenerated

#endif /* QueryPlan1CONSTRAINT_H_ */
