/*
 * ConstraintTestPlan1414068524245Constraint.cpp
 *
 *  Created on: Oct 23, 2014
 *      Author: Philipp
 */

#include <ConstraintTestPlan1414068524245Constraint.h>

#include "engine/constraintmodul/ConstraintDescriptor.h"
#include "engine/RunningPlan.h"

namespace alicaAutogenerated
{

	void Constraint1414068566297::getConstraint(shared_ptr<ConstraintDescriptor> c, shared_ptr<RunningPlan> rp)
	{

	}
} /* namespace alica */
