/*
 * ConstraintTestPlan1414068524245.cpp
 *
 *  Created on: Oct 23, 2014
 *      Author: Philipp
 */

#include "ConstraintTestPlan1414068524245.h"

#include "engine/DefaultUtilityFunction.h"

namespace alicaAutogenerated
{

	shared_ptr<UtilityFunction> UtilityFunction1414068524245::getUtilityFunction(Plan* plan)
	{
		shared_ptr<UtilityFunction> defaultFunction = make_shared<DefaultUtilityFunction>(plan);
		return defaultFunction;
	}

	bool RunTimeCondition1414068566297::evaluate(shared_ptr<RunningPlan> rp)
	{
		return true;
	}

} /* namespace alica */
