/*
 * MultiAgentTestMaster1413200842973.cpp
 *
 *  Created on: Oct 13, 2014
 *      Author: Stefan Jakob
 */

#include "MultiAgentTestMaster1413200842973.h"

namespace alicaAutogenerated
{

	shared_ptr<UtilityFunction> UtilityFunction1413200842973::getUtilityFunction(Plan* plan)
	{
		shared_ptr<UtilityFunction> defaultFunction = make_shared<DefaultUtilityFunction>(plan);
		return defaultFunction;
	}

	bool TransitionCondition1413201227586::evaluate(shared_ptr<RunningPlan> rp)
	{
		return rp->anyChildrenStatus(PlanStatus::Success);
		//return rp->anyChildrenTaskSuccess();
	}

	bool TransitionCondition1413201389955::evaluate(shared_ptr<RunningPlan> rp)
	{
		return rp->anyChildrenStatus(PlanStatus::Success);
		//return rp->anyChildrenTaskSuccess();
	}
} /* namespace alica */
