/*
 * MultiAgentTestPlan1413200862180.cpp
 *
 *  Created on: Oct 13, 2014
 *      Author: Stefan Jakob
 */

#include <MultiAgentTestPlan1413200862180.h>

namespace alicaAutogenerated
{

	shared_ptr<UtilityFunction> UtilityFunction1413200862180::getUtilityFunction(Plan* plan)
	{
		shared_ptr<UtilityFunction> defaultFunction = make_shared<DefaultUtilityFunction>(plan);
		return defaultFunction;
	}

	bool TransitionCondition1413201052549::evaluate(shared_ptr<RunningPlan> rp)
	{
		return rp->anyChildrenStatus(PlanStatus::Success);
		//return rp->anyChildrenTaskSuccess();
	}

	bool TransitionCondition1413201367990::evaluate(shared_ptr<RunningPlan> rp)
	{
		return rp->anyChildrenStatus(PlanStatus::Success);
		//return rp->anyChildrenTaskSuccess();
	}

	bool TransitionCondition1413201370590::evaluate(shared_ptr<RunningPlan> rp)
	{
		return rp->anyChildrenStatus(PlanStatus::Success);
		//return rp->anyChildrenTaskSuccess();
	}

} /* namespace alica */
