/*
 * SimpleTestPlan1412252439925Constraint.cpp
 *
 *  Created on: Oct 8, 2014
 *      Author: Stefan Jakob
 */

#include "SimpleTestPlan1412252439925Constraint.h"
#include "engine/constraintmodul/ConstraintDescriptor.h"
#include "engine/RunningPlan.h"

using namespace std;
using namespace alica;

namespace alicaAutogenerated
{

	void Constraint1412781693884::getConstraint(shared_ptr<ConstraintDescriptor> c, shared_ptr<RunningPlan> rp)
	{

	}

} /* namespace alica */

