/*
 * TestUtilityFunctionCreator.cpp
 *
 *  Created on: Oct 8, 2014
 *      Author: Stefan Jakob
 */

#include "TestUtilityFunctionCreator.h"
#include "SimpleTestPlan1412252439925.h"
#include "engine/BasicUtilityFunction.h"

#include <iostream>

using namespace std;
using namespace alicaAutogenerated;

namespace alica
{

	TestUtilityFunctionCreator::~TestUtilityFunctionCreator()
	{
	}

	TestUtilityFunctionCreator::TestUtilityFunctionCreator()
	{
	}

	shared_ptr<BasicUtilityFunction> TestUtilityFunctionCreator::createUtility(long utilityfunctionConfId)
	{
		switch (utilityfunctionConfId)
		{
			case 1412252439925:
				return make_shared<UtilityFunction1412252439925>();
				break;
			default:
			cerr << "TestUtilityFunctionCreator: Unknown utility function id requested: " << utilityfunctionConfId << endl;
			throw new exception();
			break;
		}
		return nullptr;
	}

} /* namespace alica */
