/*
 * TestConstraintCreator.cpp
 *
 *  Created on: Oct 8, 2014
 *      Author: Stefan Jakob
 */

#include "TestConstraintCreator.h"
#include "ConstraintTestPlan1414068524245Constraint.h"
#include <iostream>

using namespace std;
using namespace alicaAutogenerated;

namespace alicaTests
{

	TestConstraintCreator::TestConstraintCreator()
	{
		// TODO Auto-generated constructor stub

	}

	TestConstraintCreator::~TestConstraintCreator()
	{
		// TODO Auto-generated destructor stub
	}

	shared_ptr<alica::BasicConstraint> TestConstraintCreator::createConstraint(long constraintConfId)
	{
		switch (constraintConfId)
		{

			case 1412781693884:
				//return make_shared<Constraint1412781707952>();
				break;
			case 1402489460549:
			case 1402489462088:
			case 1403773741874:

			case 1414068566297:
				return make_shared<Constraint1414068566297>();
				break;

			default:
				cerr << "TestConstraintCreator: Unknown constraint id requested: " << constraintConfId << endl;
				throw new exception();
				break;
		}
	}

} /* namespace alica */
