/*
 * TestConditionCreator.cpp
 *
 *  Created on: Oct 8, 2014
 *      Author: Stefan Jakob
 */

#include "TestConditionCreator.h"
#include "SimpleTestPlan1412252439925.h"
#include "MultiAgentTestMaster1413200842973.h"
#include "MultiAgentTestPlan1413200862180.h"
#include "engine/expressionhandler/BasicFalseCondition.h"

using namespace alicaAutogenerated;

namespace alica
{

	TestConditionCreator::TestConditionCreator()
	{

	}

	TestConditionCreator::~TestConditionCreator()
	{
	}

	shared_ptr<BasicCondition> TestConditionCreator::createConditions(long conditionConfId)
	{
		switch (conditionConfId)
		{
			case 1412781707952:
				return make_shared<PreCondition1412781707952>();
				break;

			case 1412781693884:
				return make_shared<RunTimeCondition1412781693884>();
				break;

			case 1412761926856:
				return make_shared<TransitionCondition1412761926856>();
				break;

			case 1413201227586:
				return make_shared<TransitionCondition1413201227586>();
				break;
			case 1413201389955:
				return make_shared<TransitionCondition1413201389955>();
				break;

			case 1413201052549:
				return make_shared<TransitionCondition1413201052549>();
				break;
			case 1413201367990:
				return make_shared<TransitionCondition1413201367990>();
				break;
			case 1413201370590:
				return make_shared<TransitionCondition1413201370590>();
				break;
			case 1409218319990:
			case 1402488558741:
			case 1402488520968:
			case 1402488519140:
			case 1402489462088:
			case 1402489460549:
			case 1402489260911:
			case 1402500844446:
			case 1402489278408:
			case 1402489258509:
			case 1402489131988:
			case 1403773741874:
			case 1402489218027:
			case 1402489206278:
			case 1402489174338:
			case 1402489073613:
			case 1402489065962:
			case 1402488993122:
			case 1402488991641:
				return make_shared<BasicFalseCondition>();
				break;
			default:
				cerr << "TestConditionCreator: Unknown condition id requested: " << conditionConfId << endl;
				throw new exception();
				break;
		}
	}

} /* namespace alica */
