/*
 * TestConditionCreator.cpp
 *
 *  Created on: Oct 8, 2014
 *      Author: Stefan Jakob
 */

#include "TestConditionCreator.h"
#include "SimpleTestPlan1412252439925.h"
#include "engine/expressionhandler/BasicFalseCondition.h"

using namespace alicaAutogenerated;

namespace alica
{

	TestConditionCreator::TestConditionCreator()
	{

	}

	TestConditionCreator::~TestConditionCreator()
	{
	}

	shared_ptr<BasicCondition> TestConditionCreator::createConditions(long conditionConfId)
	{
		switch (conditionConfId)
		{
			case 1412781707952:
				return make_shared<PreCondition1412781707952>();
				break;

			case 1412781693884:
				return make_shared<RunTimeCondition1412781693884>();
				break;

			case 1412761926856:
				return make_shared<TransitionCondition1412761926856>();
				break;
			default:
			cerr << "TestConditionCreator: Unknown condition id requested: " << conditionConfId << endl;
			return make_shared<BasicFalseCondition>();
			throw new exception();
			break;
		}
	}

} /* namespace alica */
