#ifndef AuthorityTest_H_
#define AuthorityTest_H_

#include "engine/BasicCondition.h"
#include "engine/BasicUtilityFunction.h"
#include "engine/UtilityFunction.h"
#include "engine/DefaultUtilityFunction.h"
/*PROTECTED REGION ID(incl1414403413451) ENABLED START*/
//Add inlcudes here
/*PROTECTED REGION END*/
using namespace alica;

namespace alicaAutogenerated
{
/*PROTECTED REGION ID(meth1414403413451) ENABLED START*/
//Add other things here
/*PROTECTED REGION END*/
class UtilityFunction1414403413451 : public BasicUtilityFunction
{
  shared_ptr<UtilityFunction> getUtilityFunction(Plan* plan);
};

} /* namespace alica */

#endif
