#ifndef Master_H_
#define Master_H_

#include "DomainCondition.h"
#include "engine/BasicUtilityFunction.h"
#include "engine/UtilityFunction.h"
#include "engine/DefaultUtilityFunction.h"
/*PROTECTED REGION ID(incl1542881176278) ENABLED START*/
// Add inlcudes here
/*PROTECTED REGION END*/
using namespace alica;

namespace alicaAutogenerated {
/*PROTECTED REGION ID(meth1542881176278) ENABLED START*/
// Add other things here
/*PROTECTED REGION END*/
class UtilityFunction1542881176278 : public BasicUtilityFunction {
    shared_ptr<UtilityFunction> getUtilityFunction(Plan* plan);
};

class TransitionCondition1542881647180 : public DomainCondition {
    bool evaluate(shared_ptr<RunningPlan> rp);
};

class TransitionCondition1542881650423 : public DomainCondition {
    bool evaluate(shared_ptr<RunningPlan> rp);
};

}  // namespace alicaAutogenerated

#endif
