#ifndef Move_H_
#define Move_H_

#include "DomainCondition.h"
#include "engine/BasicUtilityFunction.h"
#include "engine/UtilityFunction.h"
#include "engine/DefaultUtilityFunction.h"
/*PROTECTED REGION ID(incl1542882005838) ENABLED START*/
// Add inlcudes here
/*PROTECTED REGION END*/
using namespace alica;

namespace alicaAutogenerated {
/*PROTECTED REGION ID(meth1542882005838) ENABLED START*/
// Add other things here
/*PROTECTED REGION END*/
class UtilityFunction1542882005838 : public BasicUtilityFunction {
    shared_ptr<UtilityFunction> getUtilityFunction(Plan* plan);
};

class RunTimeCondition1543284793605 : public DomainCondition {
    bool evaluate(shared_ptr<RunningPlan> rp);
};

}  // namespace alicaAutogenerated

#endif
