#ifndef AttackPlanCONSTRAINT_H_
#define AttackPlan_H_
#include "engine/BasicConstraint.h"
#include <memory>

using namespace std;
using namespace alica;

namespace alica
{
class ProblemDescriptor;
class RunningPlan;
}

namespace alicaAutogenerated
{

class Constraint1402489460549 : public BasicConstraint
{
  void getConstraint(shared_ptr<ProblemDescriptor> c, shared_ptr<RunningPlan>);
};

class Constraint1402489462088 : public BasicConstraint
{
  void getConstraint(shared_ptr<ProblemDescriptor> c, shared_ptr<RunningPlan>);
};

} /* namespace alica */

#endif /* AttackPlanCONSTRAINT_H_ */
