#ifndef DefendCONSTRAINT_H_
#define Defend_H_
#include "engine/BasicConstraint.h"
#include <memory>

using namespace std;
using namespace alica;

namespace alica
{
class ConstraintDescriptor;
class RunningPlan;
}

namespace alicaAutogenerated
{

} /* namespace alica */

#endif /* DefendCONSTRAINT_H_ */
