#ifndef DefendCONSTRAINT_H_
#define Defend_H_
#include "engine/BasicConstraint.h"
#include <memory>

using namespace std;
using namespace alica;

namespace alica
{
class ConstraintDescriptor;
class RunningPlan;
}

namespace alicaAutogenerated
{

class Constraint1402488991641 : public BasicConstraint
{
  void getConstraint(shared_ptr<ConstraintDescriptor> c, shared_ptr<RunningPlan>);
};

class Constraint1402488993122 : public BasicConstraint
{
  void getConstraint(shared_ptr<ConstraintDescriptor> c, shared_ptr<RunningPlan>);
};

class Constraint1402489065962 : public BasicConstraint
{
  void getConstraint(shared_ptr<ConstraintDescriptor> c, shared_ptr<RunningPlan>);
};

class Constraint1402489073613 : public BasicConstraint
{
  void getConstraint(shared_ptr<ConstraintDescriptor> c, shared_ptr<RunningPlan>);
};

} /* namespace alica */

#endif /* DefendCONSTRAINT_H_ */
