#ifndef MasterPlanCONSTRAINT_H_
#define MasterPlan_H_
#include "engine/BasicConstraint.h"
#include <memory>

using namespace std;
using namespace alica;

namespace alica
{
class ProblemDescriptor;
class RunningPlan;
}

namespace alicaAutogenerated
{

} /* namespace alica */

#endif /* MasterPlanCONSTRAINT_H_ */
