#ifndef MasterSyncTransitionCONSTRAINT_H_
#define MasterSyncTransition_H_
#include "engine/BasicConstraint.h"
#include <memory>

using namespace std;
using namespace alica;

namespace alica
{
    class ConstraintDescriptor;
    class RunningPlan;
}

namespace alicaAutogenerated
{

} /* namespace alica */

#endif /* MasterSyncTransitionCONSTRAINT_H_ */
