#ifndef MasterPlanTaskAssignmentCONSTRAINT_H_
#define MasterPlanTaskAssignment_H_
#include "engine/BasicConstraint.h"
#include <memory>

using namespace std;
using namespace alica;

namespace alica
{
class ProblemDescriptor;
class RunningPlan;
}

namespace alicaAutogenerated
{

} /* namespace alica */

#endif /* MasterPlanTaskAssignmentCONSTRAINT_H_ */
