#ifndef MasterPlanTestConditionPlanTypeCONSTRAINT_H_
#define MasterPlanTestConditionPlanType_H_
#include "engine/BasicConstraint.h"
#include <memory>

using namespace std;
using namespace alica;

namespace alica
{
    class ConstraintDescriptor;
    class RunningPlan;
}

namespace alicaAutogenerated
{

} /* namespace alica */

#endif /* MasterPlanTestConditionPlanTypeCONSTRAINT_H_ */
