#ifndef MasterPlanCONSTRAINT_H_
#define MasterPlan_H_
#include "engine/BasicConstraint.h"
#include <memory>

using namespace std;
using namespace alica;

namespace alica
{
class ConstraintDescriptor;
class RunningPlan;
}

namespace alicaAutogenerated
{

class Constraint1402488519140 : public BasicConstraint
{
  void getConstraint(shared_ptr<ConstraintDescriptor> c, shared_ptr<RunningPlan>);
};

class Constraint1402488520968 : public BasicConstraint
{
  void getConstraint(shared_ptr<ConstraintDescriptor> c, shared_ptr<RunningPlan>);
};

class Constraint1402488558741 : public BasicConstraint
{
  void getConstraint(shared_ptr<ConstraintDescriptor> c, shared_ptr<RunningPlan>);
};

class Constraint1409218319990 : public BasicConstraint
{
  void getConstraint(shared_ptr<ConstraintDescriptor> c, shared_ptr<RunningPlan>);
};

} /* namespace alica */

#endif /* MasterPlanCONSTRAINT_H_ */
