#ifndef MidFieldPlayPlanCONSTRAINT_H_
#define MidFieldPlayPlan_H_
#include "engine/BasicConstraint.h"
#include <memory>

using namespace std;
using namespace alica;

namespace alica
{
class ConstraintDescriptor;
class RunningPlan;
}

namespace alicaAutogenerated
{

class Constraint1402489260911 : public BasicConstraint
{
  void getConstraint(shared_ptr<ConstraintDescriptor> c, shared_ptr<RunningPlan>);
};

class Constraint1402489258509 : public BasicConstraint
{
  void getConstraint(shared_ptr<ConstraintDescriptor> c, shared_ptr<RunningPlan>);
};

class Constraint1402489278408 : public BasicConstraint
{
  void getConstraint(shared_ptr<ConstraintDescriptor> c, shared_ptr<RunningPlan>);
};

class Constraint1402500844446 : public BasicConstraint
{
  void getConstraint(shared_ptr<ConstraintDescriptor> c, shared_ptr<RunningPlan>);
};

} /* namespace alica */

#endif /* MidFieldPlayPlanCONSTRAINT_H_ */
