#ifndef MidFieldPlayPlanCONSTRAINT_H_
#define MidFieldPlayPlan_H_
#include "engine/BasicConstraint.h"
#include <memory>

using namespace std;
using namespace alica;

namespace alica
{
class ConstraintDescriptor;
class RunningPlan;
}

namespace alicaAutogenerated
{

} /* namespace alica */

#endif /* MidFieldPlayPlanCONSTRAINT_H_ */
