#ifndef MultiAgentTestPlanCONSTRAINT_H_
#define MultiAgentTestPlan_H_
#include "engine/BasicConstraint.h"
#include <memory>

using namespace std;
using namespace alica;

namespace alica
{
class ConstraintDescriptor;
class RunningPlan;
}

namespace alicaAutogenerated
{

} /* namespace alica */

#endif /* MultiAgentTestPlanCONSTRAINT_H_ */
