#ifndef MultiAgentTestPlanCONSTRAINT_H_
#define MultiAgentTestPlan_H_
#include "engine/BasicConstraint.h"
#include <memory>

using namespace std;
using namespace alica;

namespace alica
{
class ConstraintDescriptor;
class RunningPlan;
}

namespace alicaAutogenerated
{

class Constraint1413201052549 : public BasicConstraint
{
  void getConstraint(shared_ptr<ConstraintDescriptor> c, shared_ptr<RunningPlan>);
};

class Constraint1413201367990 : public BasicConstraint
{
  void getConstraint(shared_ptr<ConstraintDescriptor> c, shared_ptr<RunningPlan>);
};

class Constraint1413201370590 : public BasicConstraint
{
  void getConstraint(shared_ptr<ConstraintDescriptor> c, shared_ptr<RunningPlan>);
};

} /* namespace alica */

#endif /* MultiAgentTestPlanCONSTRAINT_H_ */
