#ifndef MultiAgentTestMasterCONSTRAINT_H_
#define MultiAgentTestMaster_H_
#include "engine/BasicConstraint.h"
#include <memory>

using namespace std;
using namespace alica;

namespace alica
{
class ConstraintDescriptor;
class RunningPlan;
}

namespace alicaAutogenerated
{

} /* namespace alica */

#endif /* MultiAgentTestMasterCONSTRAINT_H_ */
