#ifndef OtherPlanCONSTRAINT_H_
#define OtherPlan_H_
#include "engine/BasicConstraint.h"
#include <memory>

using namespace std;
using namespace alica;

namespace alica
{
    class ConstraintDescriptor;
    class RunningPlan;
}

namespace alicaAutogenerated
{

} /* namespace alica */

#endif /* OtherPlanCONSTRAINT_H_ */
