#ifndef PlanTwoCONSTRAINT_H_
#define PlanTwo_H_
#include "engine/BasicConstraint.h"
#include <memory>

using namespace std;
using namespace alica;

namespace alica
{
class ProblemDescriptor;
class RunningPlan;
}

namespace alicaAutogenerated
{

} /* namespace alica */

#endif /* PlanTwoCONSTRAINT_H_ */
