#ifndef PlanThreeCONSTRAINT_H_
#define PlanThree_H_
#include "engine/BasicConstraint.h"
#include <memory>

using namespace std;
using namespace alica;

namespace alica
{
class ConstraintDescriptor;
class RunningPlan;
}

namespace alicaAutogenerated
{

} /* namespace alica */

#endif /* PlanThreeCONSTRAINT_H_ */
