#ifndef PlanFourCONSTRAINT_H_
#define PlanFour_H_
#include "engine/BasicConstraint.h"
#include <memory>

using namespace std;
using namespace alica;

namespace alica
{
class ConstraintDescriptor;
class RunningPlan;
}

namespace alicaAutogenerated
{

} /* namespace alica */

#endif /* PlanFourCONSTRAINT_H_ */
