#ifndef PlanOneCONSTRAINT_H_
#define PlanOne_H_
#include "engine/BasicConstraint.h"
#include <memory>

using namespace std;
using namespace alica;

namespace alica
{
class ConstraintDescriptor;
class RunningPlan;
}

namespace alicaAutogenerated
{

} /* namespace alica */

#endif /* PlanOneCONSTRAINT_H_ */
