#ifndef SimpleTestPlanCONSTRAINT_H_
#define SimpleTestPlan_H_
#include "engine/BasicConstraint.h"
#include <memory>

using namespace std;
using namespace alica;

namespace alica
{
class ConstraintDescriptor;
class RunningPlan;
}

namespace alicaAutogenerated
{

} /* namespace alica */

#endif /* SimpleTestPlanCONSTRAINT_H_ */
