#ifndef TackleCONSTRAINT_H_
#define Tackle_H_
#include "engine/BasicConstraint.h"
#include <memory>

using namespace std;
using namespace alica;

namespace alica {
class ProblemDescriptor;
class RunningPlan;
}  // namespace alica

namespace alicaAutogenerated {}  // namespace alicaAutogenerated

#endif /* TackleCONSTRAINT_H_ */
