#include "Plans/VariableHandling/Lvl21524452793378.h"
using namespace alica;
/*PROTECTED REGION ID(eph1524452793378) ENABLED START*/ // Add additional using directives here
/*PROTECTED REGION END*/
namespace alicaAutogenerated
{
// Plan:Lvl2

// Check of RuntimeCondition - (Name): NewRuntimeCondition, (ConditionString): , (Comment) :

/*
 * Available Vars:
 *	- L2A (1524453150187)
 *	- L2B (1524453155043)
 *	- L2C (1524453162883)
 */
bool RunTimeCondition1524453266123::evaluate(shared_ptr<RunningPlan> rp)
{
    /*PROTECTED REGION ID(1524453266123) ENABLED START*/
    return true;
    /*PROTECTED REGION END*/
}

/* generated comment

 Task: DefaultTask  -> EntryPoint-ID: 1524452793380

 Task: AttackTask  -> EntryPoint-ID: 1524453238753

 */
shared_ptr<UtilityFunction> UtilityFunction1524452793378::getUtilityFunction(Plan* plan)
{
    /*PROTECTED REGION ID(1524452793378) ENABLED START*/

    shared_ptr<UtilityFunction> defaultFunction = make_shared<DefaultUtilityFunction>(plan);
    return defaultFunction;

    /*PROTECTED REGION END*/
}

// State: NewState in Plan: Lvl2

// State: Dummy in Plan: Lvl2
} // namespace alicaAutogenerated
