name: Build and Test
on:
  workflow_dispatch:
    inputs:
      email:
        description: "Email to send result to"
        type: string
        required: true
jobs:
  run_coverity_scan:
    runs-on: "${{ matrix.os }}"
    steps:
      - uses: actions/checkout@v3
      - uses: vapier/coverity-scan-action@v1
        with:
          email: ${{ inputs.email }}
          token: ${{ secrets.COVERITY_SCAN_TOKEN }}
