name: Build and Test
on:
  push:
    branches:
      - devel
  pull_request:
    branches:
      - devel
  workflow_dispatch:
jobs:
  ROS2_build_test:
    runs-on: "${{ matrix.os }}"
    timeout-minutes: 10
    strategy:
      matrix:
        os:
          - ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Pull ROS2 images
        run: docker pull ros:humble
      - name: Build and test Alica on ROS2 Humble
        uses: docker/build-push-action@v3
        with:
          context: .
          file: "./.github/workflows/ros2_build_test/Dockerfile"
          platforms: linux/amd64
          push: false
          tags: humble
          build-args: |
            COMMIT=${{ github.sha }}
